// 검수 완료 JSON(question_pipeline/reviewed/) → src/data/questionBank/part1~7.ts 변환기.
// 1번 에이전트(저장소 통합 검수)가 사용한다. 사용법: node question_pipeline/build_bank.cjs
const fs = require('fs');
const path = require('path');

const REVIEWED_DIR = path.join(__dirname, 'reviewed');
const OUT_DIR = path.join(__dirname, '..', 'src', 'data', 'questionBank');

const FILES = {
  1: 'lc_part1.json',
  2: 'lc_part2.json',
  3: 'lc_part3.json',
  4: 'lc_part4.json',
  5: 'rc_part5.json',
  6: 'rc_part6.json',
  7: 'rc_part7.json'
};

function readJson(file) {
  const p = path.join(REVIEWED_DIR, file);
  if (!fs.existsSync(p)) return [];
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch (e) {
    console.error(`[skip] ${file}: JSON parse error — ${e.message}`);
    return [];
  }
}

// Part 7은 지문 단위 그룹 형식({passage, questions:[...]})과 평탄화 형식 모두 허용
function flatten(part, raw) {
  const items = [];
  for (const entry of raw) {
    if (Array.isArray(entry.questions)) {
      for (const q of entry.questions) {
        items.push({ ...q, part, type: part <= 4 ? 'LC' : 'RC', passage: entry.passage });
      }
    } else {
      items.push(entry);
    }
  }
  return items;
}

function validate(part, item) {
  const errors = [];
  const type = part <= 4 ? 'LC' : 'RC';
  if (typeof item.question !== 'string' || !item.question.trim()) errors.push('question 누락');
  if (!Array.isArray(item.options) || item.options.some(o => typeof o !== 'string' || !o.trim())) errors.push('options 형식 오류');
  else {
    const expected = part === 2 ? 3 : 4;
    if (item.options.length !== expected) errors.push(`options 개수 ${item.options.length} (기대: ${expected})`);
  }
  if (!Number.isInteger(item.answer) || item.answer < 0 || (Array.isArray(item.options) && item.answer >= item.options.length)) errors.push('answer 인덱스 오류');
  if (typeof item.explanation !== 'string' || !item.explanation.trim()) errors.push('explanation 누락');
  if (type === 'LC' && (typeof item.script !== 'string' || !item.script.trim())) errors.push('LC script 누락');
  if ((part === 6 || part === 7) && (typeof item.passage !== 'string' || !item.passage.trim())) errors.push('passage 누락');
  if (part === 5 && item.passage) errors.push('Part 5에 passage 존재');
  // 빈칸 마커 표준은 _______(7개)이지만, 검사 목적은 "빈칸 존재 여부"이므로 표기 변형에 견고하도록 3개 이상을 허용한다
  if (part === 6 && item.passage && !/_{3,}/.test(item.passage)) errors.push('Part 6 passage에 빈칸 없음');
  // Part 7의 클로즈 빈칸 컨벤션은 7개 언더스코어. 짧은 밑줄(____)은 양식 미기입 필드 재현이므로 허용한다
  if (part === 7 && item.passage && item.passage.includes('_______')) errors.push('Part 7 passage에 빈칸 존재');
  if (item.difficulty && !['easy', 'medium', 'hard'].includes(item.difficulty)) errors.push(`difficulty 값 오류: "${item.difficulty}"`);
  return errors;
}

function emit(part, items) {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const header = '// Auto-generated by question_pipeline/build_bank.cjs — 직접 수정하지 마세요.\n' +
    '// 데이터 출처: question_pipeline/reviewed/ (에이전트 파이프라인 검수 완료분)\n';
  const body = `import { BankQuestion } from './index';\n\nexport const PART${part}_QUESTIONS: BankQuestion[] = ${JSON.stringify(items, null, 2)};\n`;
  fs.writeFileSync(path.join(OUT_DIR, `part${part}.ts`), header + body);
}

const summary = [];
for (const [partStr, file] of Object.entries(FILES)) {
  const part = Number(partStr);
  const type = part <= 4 ? 'LC' : 'RC';
  const raw = flatten(part, readJson(file));
  const seen = new Set();
  const accepted = [];
  let rejected = 0;
  for (const item of raw) {
    const errors = validate(part, item);
    const key = `${item.question}|${item.script || ''}|${item.passage || ''}`;
    if (errors.length > 0) {
      rejected++;
      console.error(`[reject] part${part}: ${errors.join(', ')} — "${String(item.question).slice(0, 60)}"`);
      continue;
    }
    if (seen.has(key)) {
      rejected++;
      console.warn(`[duplicate] part${part}: "${String(item.question).slice(0, 60)}"`);
      continue;
    }
    seen.add(key);
    accepted.push({
      id: `p${part}-${String(accepted.length + 1).padStart(4, '0')}`,
      part,
      type,
      question: item.question.trim(),
      ...(item.script ? { script: item.script.trim() } : {}),
      ...(item.passage ? { passage: item.passage.trim() } : {}),
      options: item.options.map(o => o.trim()),
      answer: item.answer,
      explanation: item.explanation.trim(),
      ...(item.difficulty ? { difficulty: item.difficulty } : {})
    });
  }
  emit(part, accepted);
  summary.push({ part, accepted: accepted.length, rejected });
}

console.log('\n=== Question Bank Build Summary ===');
for (const s of summary) console.log(`Part ${s.part}: 채택 ${s.accepted} / 반려 ${s.rejected}`);
console.log(`총 채택: ${summary.reduce((a, s) => a + s.accepted, 0)}`);
