// Auto-generated by question_pipeline/build_bank.cjs — 직접 수정하지 마세요.
// 데이터 출처: question_pipeline/reviewed/ (에이전트 파이프라인 검수 완료분)
import { BankQuestion } from './index';

export const PART3_QUESTIONS: BankQuestion[] = [
  {
    "id": "p3-0001",
    "part": 3,
    "type": "LC",
    "question": "What are the speakers mainly discussing?",
    "script": "M: Hi Rachel, have you seen the memo about moving to the new building on Hartfield Avenue? W: Yes, I just read it. We are supposed to pack up our desks by Friday afternoon. M: That seems rushed. I still have dozens of client files to organize. W: Don't worry. Facilities is providing labeled boxes, and the movers will handle everything over the weekend. M: That's a relief. Do you know if we get to choose our seats in the new office? W: No, the seating chart was already finalized. It will be posted on the intranet tomorrow morning.",
    "options": [
      "An upcoming office relocation",
      "A client presentation schedule",
      "A new filing software system",
      "A weekend training seminar"
    ],
    "answer": 0,
    "explanation": "대화의 첫 부분에서 남자가 'have you seen the memo about moving to the new building'이라고 말하며 새 건물로의 이전을 언급하고, 이후 짐 싸기, 이사 업체, 좌석 배치 등 사무실 이전과 관련된 내용이 계속 이어집니다. 따라서 정답은 (A) An upcoming office relocation입니다. 발표 일정, 소프트웨어, 교육 세미나는 대화에서 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0002",
    "part": 3,
    "type": "LC",
    "question": "What is the man concerned about?",
    "script": "M: Hi Rachel, have you seen the memo about moving to the new building on Hartfield Avenue? W: Yes, I just read it. We are supposed to pack up our desks by Friday afternoon. M: That seems rushed. I still have dozens of client files to organize. W: Don't worry. Facilities is providing labeled boxes, and the movers will handle everything over the weekend. M: That's a relief. Do you know if we get to choose our seats in the new office? W: No, the seating chart was already finalized. It will be posted on the intranet tomorrow morning.",
    "options": [
      "Losing some important clients",
      "The cost of hiring professional movers",
      "Having enough time to organize his files",
      "Finding parking at the new building"
    ],
    "answer": 2,
    "explanation": "남자는 'That seems rushed. I still have dozens of client files to organize.'라고 말하며 금요일까지 짐을 싸야 하는 일정이 촉박하고, 아직 정리해야 할 고객 파일이 많다는 점을 걱정하고 있습니다. 따라서 정답은 (C)입니다. 고객을 잃는 것, 이사 비용, 주차 문제는 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0003",
    "part": 3,
    "type": "LC",
    "question": "According to the woman, what will be posted on the intranet tomorrow?",
    "script": "M: Hi Rachel, have you seen the memo about moving to the new building on Hartfield Avenue? W: Yes, I just read it. We are supposed to pack up our desks by Friday afternoon. M: That seems rushed. I still have dozens of client files to organize. W: Don't worry. Facilities is providing labeled boxes, and the movers will handle everything over the weekend. M: That's a relief. Do you know if we get to choose our seats in the new office? W: No, the seating chart was already finalized. It will be posted on the intranet tomorrow morning.",
    "options": [
      "A packing checklist",
      "A building map",
      "A seating chart",
      "A moving company contract"
    ],
    "answer": 2,
    "explanation": "대화 마지막에 여자가 'the seating chart was already finalized. It will be posted on the intranet tomorrow morning.'이라고 말합니다. 즉, 내일 아침 인트라넷에 게시되는 것은 좌석 배치도(seating chart)이므로 정답은 (C)입니다. 포장 체크리스트나 건물 지도, 계약서는 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0004",
    "part": 3,
    "type": "LC",
    "question": "Who most likely is the woman?",
    "script": "W: Good morning, Mr. Delgado. This is Priya Shah calling from the human resources department at Norwick Solutions. We reviewed your application for the financial analyst position, and we would like to invite you for an interview. M: That's wonderful news! Thank you so much. When would the interview take place? W: We have openings next Tuesday at ten a.m. or Thursday at two p.m. The interview will last about an hour and includes a short written exercise. M: Thursday at two works better for me. I have a prior commitment on Tuesday morning. W: Perfect. I'll send you a confirmation e-mail with directions to our office and a list of documents to bring. M: Great. I'll watch for your e-mail. Thank you again.",
    "options": [
      "A financial analyst",
      "A bank teller",
      "A human resources employee",
      "A receptionist at a clinic"
    ],
    "answer": 2,
    "explanation": "여자는 첫 대사에서 'This is Priya Shah calling from the human resources department at Norwick Solutions.'라고 자신을 소개합니다. 인사부(human resources department) 소속임을 직접 밝히고 있으므로 정답은 (C)입니다. (A) financial analyst는 남자가 지원한 직무이므로 혼동하지 않도록 주의해야 합니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0005",
    "part": 3,
    "type": "LC",
    "question": "Why is the man unavailable on Tuesday?",
    "script": "W: Good morning, Mr. Delgado. This is Priya Shah calling from the human resources department at Norwick Solutions. We reviewed your application for the financial analyst position, and we would like to invite you for an interview. M: That's wonderful news! Thank you so much. When would the interview take place? W: We have openings next Tuesday at ten a.m. or Thursday at two p.m. The interview will last about an hour and includes a short written exercise. M: Thursday at two works better for me. I have a prior commitment on Tuesday morning. W: Perfect. I'll send you a confirmation e-mail with directions to our office and a list of documents to bring. M: Great. I'll watch for your e-mail. Thank you again.",
    "options": [
      "He will be traveling abroad",
      "He has to take a written exam",
      "He has another appointment",
      "His car is being repaired"
    ],
    "answer": 2,
    "explanation": "남자는 'I have a prior commitment on Tuesday morning.'이라고 말하며 화요일 오전에 선약이 있다고 밝힙니다. prior commitment(선약)를 another appointment로 바꾸어 표현한 (C)가 정답입니다. 해외여행, 필기시험, 차량 수리는 대화에 등장하지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0006",
    "part": 3,
    "type": "LC",
    "question": "What does the woman say she will do?",
    "script": "W: Good morning, Mr. Delgado. This is Priya Shah calling from the human resources department at Norwick Solutions. We reviewed your application for the financial analyst position, and we would like to invite you for an interview. M: That's wonderful news! Thank you so much. When would the interview take place? W: We have openings next Tuesday at ten a.m. or Thursday at two p.m. The interview will last about an hour and includes a short written exercise. M: Thursday at two works better for me. I have a prior commitment on Tuesday morning. W: Perfect. I'll send you a confirmation e-mail with directions to our office and a list of documents to bring. M: Great. I'll watch for your e-mail. Thank you again.",
    "options": [
      "Send a confirmation e-mail",
      "Reschedule the interview",
      "Forward his résumé to a manager",
      "Reserve a meeting room"
    ],
    "answer": 0,
    "explanation": "여자는 마지막 대사에서 'I'll send you a confirmation e-mail with directions to our office and a list of documents to bring.'이라고 말합니다. 확인 이메일을 보내겠다는 내용이므로 정답은 (A)입니다. 면접 일정 변경이나 이력서 전달, 회의실 예약은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0007",
    "part": 3,
    "type": "LC",
    "question": "What department do the speakers most likely work in?",
    "script": "W: Tom, the engagement numbers for our spring social media campaign just came in. Click-through rates are up thirty percent compared to last quarter. M: That's impressive. The short video clips we posted must be resonating with younger customers. W: Exactly. I think we should shift more of our advertising budget toward video content for the summer campaign. M: I agree, but we'd need approval from the director first. She was hesitant about cutting the print ads. W: Then let's put together a one-page summary of these results before our meeting with her on Thursday. M: Good idea. I'll draft the summary tonight and send it to you for feedback.",
    "options": [
      "Accounting",
      "Marketing",
      "Information technology",
      "Customer service"
    ],
    "answer": 1,
    "explanation": "대화에서 social media campaign(소셜 미디어 캠페인), click-through rates(클릭률), advertising budget(광고 예산), print ads(인쇄 광고) 등 마케팅 관련 용어가 계속 등장합니다. 두 화자는 광고 캠페인의 성과를 분석하고 다음 캠페인 전략을 논의하고 있으므로 마케팅 부서에서 일한다고 추론할 수 있습니다. 정답은 (B)입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0008",
    "part": 3,
    "type": "LC",
    "question": "What does the woman suggest doing?",
    "script": "W: Tom, the engagement numbers for our spring social media campaign just came in. Click-through rates are up thirty percent compared to last quarter. M: That's impressive. The short video clips we posted must be resonating with younger customers. W: Exactly. I think we should shift more of our advertising budget toward video content for the summer campaign. M: I agree, but we'd need approval from the director first. She was hesitant about cutting the print ads. W: Then let's put together a one-page summary of these results before our meeting with her on Thursday. M: Good idea. I'll draft the summary tonight and send it to you for feedback.",
    "options": [
      "Hiring a video production company",
      "Canceling the summer campaign",
      "Allocating more budget to video content",
      "Conducting a customer survey"
    ],
    "answer": 2,
    "explanation": "여자는 'I think we should shift more of our advertising budget toward video content for the summer campaign.'이라고 말하며 여름 캠페인에서 광고 예산을 영상 콘텐츠 쪽으로 더 옮기자고 제안합니다. shift more of our advertising budget toward video content를 allocating more budget to video content로 바꾸어 쓴 (C)가 정답입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0009",
    "part": 3,
    "type": "LC",
    "question": "What will the man do tonight?",
    "script": "W: Tom, the engagement numbers for our spring social media campaign just came in. Click-through rates are up thirty percent compared to last quarter. M: That's impressive. The short video clips we posted must be resonating with younger customers. W: Exactly. I think we should shift more of our advertising budget toward video content for the summer campaign. M: I agree, but we'd need approval from the director first. She was hesitant about cutting the print ads. W: Then let's put together a one-page summary of these results before our meeting with her on Thursday. M: Good idea. I'll draft the summary tonight and send it to you for feedback.",
    "options": [
      "Meet with the director",
      "Film a new video clip",
      "Write a summary document",
      "Revise the print advertisements"
    ],
    "answer": 2,
    "explanation": "남자는 마지막 대사에서 'I'll draft the summary tonight and send it to you for feedback.'이라고 말합니다. 오늘 밤에 요약본 초안을 작성하겠다는 의미이므로 정답은 (C)입니다. 이사와의 회의는 목요일에 예정되어 있고, 영상 촬영이나 인쇄 광고 수정은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0010",
    "part": 3,
    "type": "LC",
    "question": "What problem is the woman reporting?",
    "script": "W: Hello, this is Dana Brooks on the fourth floor. The air conditioning in our conference room has stopped working, and we have a client meeting in there at two o'clock. M: I'm sorry to hear that, Ms. Brooks. Our maintenance team is currently repairing an elevator, so the earliest we could look at it is around three thirty. W: That's after our meeting starts. Is there anything else you can do? M: Well, the small meeting room on the fifth floor is available all afternoon, and its cooling system works fine. I could reserve it for you right now. W: Yes, please do that. And could you have someone put a sign on the fourth-floor room redirecting our visitors? M: Certainly. I'll print a notice and post it within the hour.",
    "options": [
      "An elevator is out of service",
      "A conference room is double-booked",
      "An air conditioner is not working",
      "A client canceled a meeting"
    ],
    "answer": 2,
    "explanation": "여자는 첫 대사에서 'The air conditioning in our conference room has stopped working'이라고 말하며 회의실 에어컨이 작동하지 않는다는 문제를 알리고 있습니다. 따라서 정답은 (C)입니다. 엘리베이터 수리는 남자의 정비팀이 현재 하고 있는 일이며, 여자가 신고한 문제가 아닙니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0011",
    "part": 3,
    "type": "LC",
    "question": "Why is the maintenance team unavailable until three thirty?",
    "script": "W: Hello, this is Dana Brooks on the fourth floor. The air conditioning in our conference room has stopped working, and we have a client meeting in there at two o'clock. M: I'm sorry to hear that, Ms. Brooks. Our maintenance team is currently repairing an elevator, so the earliest we could look at it is around three thirty. W: That's after our meeting starts. Is there anything else you can do? M: Well, the small meeting room on the fifth floor is available all afternoon, and its cooling system works fine. I could reserve it for you right now. W: Yes, please do that. And could you have someone put a sign on the fourth-floor room redirecting our visitors? M: Certainly. I'll print a notice and post it within the hour.",
    "options": [
      "They are working on another repair",
      "They are attending a safety training",
      "They are short-staffed today",
      "They are waiting for replacement parts"
    ],
    "answer": 0,
    "explanation": "남자는 'Our maintenance team is currently repairing an elevator, so the earliest we could look at it is around three thirty.'라고 말합니다. 정비팀이 현재 엘리베이터를 수리 중이어서 3시 30분 이후에야 가능하다는 것이므로, 다른 수리 작업을 하고 있다는 (A)가 정답입니다. 교육, 인력 부족, 부품 대기는 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0012",
    "part": 3,
    "type": "LC",
    "question": "What does the woman ask the man to do?",
    "script": "W: Hello, this is Dana Brooks on the fourth floor. The air conditioning in our conference room has stopped working, and we have a client meeting in there at two o'clock. M: I'm sorry to hear that, Ms. Brooks. Our maintenance team is currently repairing an elevator, so the earliest we could look at it is around three thirty. W: That's after our meeting starts. Is there anything else you can do? M: Well, the small meeting room on the fifth floor is available all afternoon, and its cooling system works fine. I could reserve it for you right now. W: Yes, please do that. And could you have someone put a sign on the fourth-floor room redirecting our visitors? M: Certainly. I'll print a notice and post it within the hour.",
    "options": [
      "Call the clients to reschedule",
      "Post a sign for visitors",
      "Order a portable cooling fan",
      "Repair the elevator first"
    ],
    "answer": 1,
    "explanation": "여자는 'could you have someone put a sign on the fourth-floor room redirecting our visitors?'라고 요청합니다. 4층 회의실에 방문객을 안내하는 표지판을 붙여 달라는 부탁이므로 정답은 (B)입니다. put a sign이 post a sign으로 바뀌어 표현되었습니다. 회의 일정 변경, 선풍기 주문, 엘리베이터 우선 수리는 요청 사항이 아닙니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0013",
    "part": 3,
    "type": "LC",
    "question": "What is the purpose of the man's trip?",
    "script": "M: Hi, I need to book a flight to Singapore for the second week of July. I'm attending a trade fair there on behalf of my company. W: Certainly. Were you looking at direct flights, or would a connecting flight be acceptable? M: Direct, if possible. My schedule is tight, and I can't risk missing a connection. W: There's a direct flight departing Monday at nine a.m., but it's about two hundred dollars more than the connecting options. M: That's fine. My company covers travel expenses for business trips. Could you also arrange a hotel near the convention center? W: Of course. The Marina Grand is a five-minute walk from the venue, and it offers a corporate discount. I'll reserve a room there for you.",
    "options": [
      "To attend a trade fair",
      "To inspect a new factory",
      "To take a vacation",
      "To meet a potential investor"
    ],
    "answer": 0,
    "explanation": "남자는 첫 대사에서 'I'm attending a trade fair there on behalf of my company.'라고 말하며 회사를 대표해 무역 박람회에 참석하기 위해 싱가포르에 간다고 밝힙니다. 따라서 정답은 (A)입니다. 공장 시찰, 휴가, 투자자 미팅은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0014",
    "part": 3,
    "type": "LC",
    "question": "Why does the man prefer a direct flight?",
    "script": "M: Hi, I need to book a flight to Singapore for the second week of July. I'm attending a trade fair there on behalf of my company. W: Certainly. Were you looking at direct flights, or would a connecting flight be acceptable? M: Direct, if possible. My schedule is tight, and I can't risk missing a connection. W: There's a direct flight departing Monday at nine a.m., but it's about two hundred dollars more than the connecting options. M: That's fine. My company covers travel expenses for business trips. Could you also arrange a hotel near the convention center? W: Of course. The Marina Grand is a five-minute walk from the venue, and it offers a corporate discount. I'll reserve a room there for you.",
    "options": [
      "He dislikes long layovers at airports",
      "He gets airsick on small planes",
      "He cannot risk missing a connecting flight",
      "He wants to save money on airfare"
    ],
    "answer": 2,
    "explanation": "남자는 'My schedule is tight, and I can't risk missing a connection.'이라고 말합니다. 일정이 빡빡해서 환승 항공편을 놓칠 위험을 감수할 수 없다는 이유이므로 정답은 (C)입니다. 직항편이 200달러 더 비싸지만 회사가 비용을 부담한다고 했으므로 (D)는 오답입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0015",
    "part": 3,
    "type": "LC",
    "question": "What does the woman mention about the Marina Grand?",
    "script": "M: Hi, I need to book a flight to Singapore for the second week of July. I'm attending a trade fair there on behalf of my company. W: Certainly. Were you looking at direct flights, or would a connecting flight be acceptable? M: Direct, if possible. My schedule is tight, and I can't risk missing a connection. W: There's a direct flight departing Monday at nine a.m., but it's about two hundred dollars more than the connecting options. M: That's fine. My company covers travel expenses for business trips. Could you also arrange a hotel near the convention center? W: Of course. The Marina Grand is a five-minute walk from the venue, and it offers a corporate discount. I'll reserve a room there for you.",
    "options": [
      "It was recently renovated",
      "It is fully booked in July",
      "It has an airport shuttle",
      "It offers a corporate discount"
    ],
    "answer": 3,
    "explanation": "여자는 'The Marina Grand is a five-minute walk from the venue, and it offers a corporate discount.'라고 말합니다. 행사장에서 도보 5분 거리이며 법인 할인을 제공한다는 두 가지 정보를 주는데, 선택지 중에서는 법인 할인을 언급한 (D)가 정답입니다. 리노베이션, 공항 셔틀, 만실 여부는 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0016",
    "part": 3,
    "type": "LC",
    "question": "What event are the speakers preparing for?",
    "script": "W: Hi, I'm calling from Calloway Tech about the catering order for our company's twentieth anniversary dinner on the twenty-eighth. I'd like to confirm the final headcount. M: Of course. Right now we have you down for eighty guests with the three-course menu. W: Actually, we just received more RSVPs, so it will be ninety-five people. Also, five of them requested vegetarian meals. M: Not a problem. We'll prepare ninety-five settings, including five vegetarian plates. Will you still need our staff to set up the tables by five p.m.? W: Yes, the venue opens at four, so that gives your team an hour. Oh, and could you add a dessert station as well? M: Sure. I'll e-mail you a revised invoice with the updated total this afternoon.",
    "options": [
      "A retirement party",
      "A company anniversary dinner",
      "A product launch ceremony",
      "A charity auction"
    ],
    "answer": 1,
    "explanation": "여자는 첫 대사에서 'the catering order for our company's twentieth anniversary dinner on the twenty-eighth'라고 말하며 회사 창립 20주년 기념 만찬을 위한 케이터링 주문을 확인하고 있습니다. 따라서 정답은 (B)입니다. 은퇴 기념 파티, 제품 출시 행사, 자선 경매는 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0017",
    "part": 3,
    "type": "LC",
    "question": "What change does the woman make to the order?",
    "script": "W: Hi, I'm calling from Calloway Tech about the catering order for our company's twentieth anniversary dinner on the twenty-eighth. I'd like to confirm the final headcount. M: Of course. Right now we have you down for eighty guests with the three-course menu. W: Actually, we just received more RSVPs, so it will be ninety-five people. Also, five of them requested vegetarian meals. M: Not a problem. We'll prepare ninety-five settings, including five vegetarian plates. Will you still need our staff to set up the tables by five p.m.? W: Yes, the venue opens at four, so that gives your team an hour. Oh, and could you add a dessert station as well? M: Sure. I'll e-mail you a revised invoice with the updated total this afternoon.",
    "options": [
      "She reduces the number of courses",
      "She cancels the table setup service",
      "She changes the event date",
      "She increases the number of guests"
    ],
    "answer": 3,
    "explanation": "남자가 기존 주문은 80명 기준이라고 하자 여자는 'we just received more RSVPs, so it will be ninety-five people'라고 말하며 인원을 95명으로 늘립니다. 따라서 정답은 (D)입니다. 코스 수 축소나 날짜 변경, 테이블 세팅 취소는 없었으며, 오히려 채식 식사 5인분과 디저트 스테이션이 추가되었습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0018",
    "part": 3,
    "type": "LC",
    "question": "What will the man send this afternoon?",
    "script": "W: Hi, I'm calling from Calloway Tech about the catering order for our company's twentieth anniversary dinner on the twenty-eighth. I'd like to confirm the final headcount. M: Of course. Right now we have you down for eighty guests with the three-course menu. W: Actually, we just received more RSVPs, so it will be ninety-five people. Also, five of them requested vegetarian meals. M: Not a problem. We'll prepare ninety-five settings, including five vegetarian plates. Will you still need our staff to set up the tables by five p.m.? W: Yes, the venue opens at four, so that gives your team an hour. Oh, and could you add a dessert station as well? M: Sure. I'll e-mail you a revised invoice with the updated total this afternoon.",
    "options": [
      "A sample menu",
      "A seating arrangement",
      "An updated invoice",
      "A list of vegetarian dishes"
    ],
    "answer": 2,
    "explanation": "남자는 마지막 대사에서 'I'll e-mail you a revised invoice with the updated total this afternoon.'이라고 말합니다. 변경된 총액이 반영된 수정 청구서(revised invoice)를 보내겠다는 것이므로, 이를 updated invoice로 바꾸어 표현한 (C)가 정답입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0019",
    "part": 3,
    "type": "LC",
    "question": "What is the main topic of the conversation?",
    "script": "W1: Welcome to the team, Marcus. I'm Elena, the training coordinator, and this is Sofia from the IT department. M: Nice to meet you both. I'm excited to get started. W2: Likewise. Before your orientation session tomorrow, we need to set up your laptop and e-mail account today. M: Great. Will I also get access to the project management system? W2: Yes, but that requires approval from your team leader, which usually takes a day or two. W1: In the meantime, Marcus, here's your orientation packet. Please review the company policies section before tomorrow's nine a.m. session in Room 204. M: Will do. Should I bring anything else to the session? W1: Just a photo ID so we can issue your employee badge.",
    "options": [
      "A new employee's first-day arrangements",
      "A software system upgrade",
      "A change in company policies",
      "A team leader's retirement"
    ],
    "answer": 0,
    "explanation": "대화는 신입 사원 Marcus를 환영하면서 노트북과 이메일 계정 설정, 오리엔테이션 자료 검토, 사원증 발급 등 입사 첫날의 준비 사항을 안내하는 내용입니다. 따라서 정답은 (A)입니다. 시스템 업그레이드나 정책 변경 자체가 주제가 아니며, 회사 정책은 신입 사원이 읽어야 할 자료로만 언급됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0020",
    "part": 3,
    "type": "LC",
    "question": "According to Sofia, why might there be a delay?",
    "script": "W1: Welcome to the team, Marcus. I'm Elena, the training coordinator, and this is Sofia from the IT department. M: Nice to meet you both. I'm excited to get started. W2: Likewise. Before your orientation session tomorrow, we need to set up your laptop and e-mail account today. M: Great. Will I also get access to the project management system? W2: Yes, but that requires approval from your team leader, which usually takes a day or two. W1: In the meantime, Marcus, here's your orientation packet. Please review the company policies section before tomorrow's nine a.m. session in Room 204. M: Will do. Should I bring anything else to the session? W1: Just a photo ID so we can issue your employee badge.",
    "options": [
      "A laptop is out of stock",
      "An approval process takes time",
      "The IT department is understaffed",
      "The orientation room is being renovated"
    ],
    "answer": 1,
    "explanation": "IT 부서의 Sofia(W2)는 프로젝트 관리 시스템 접근 권한에 대해 'that requires approval from your team leader, which usually takes a day or two'라고 말합니다. 팀장의 승인이 필요하고 보통 하루 이틀 걸린다는 것이므로, 승인 절차에 시간이 걸린다는 (B)가 정답입니다. 3인 대화에서는 각 화자의 이름과 역할을 구분하여 듣는 것이 중요합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0021",
    "part": 3,
    "type": "LC",
    "question": "What is the man asked to bring tomorrow?",
    "script": "W1: Welcome to the team, Marcus. I'm Elena, the training coordinator, and this is Sofia from the IT department. M: Nice to meet you both. I'm excited to get started. W2: Likewise. Before your orientation session tomorrow, we need to set up your laptop and e-mail account today. M: Great. Will I also get access to the project management system? W2: Yes, but that requires approval from your team leader, which usually takes a day or two. W1: In the meantime, Marcus, here's your orientation packet. Please review the company policies section before tomorrow's nine a.m. session in Room 204. M: Will do. Should I bring anything else to the session? W1: Just a photo ID so we can issue your employee badge.",
    "options": [
      "A signed contract",
      "A completed survey form",
      "His personal laptop",
      "A photo identification"
    ],
    "answer": 3,
    "explanation": "남자가 'Should I bring anything else to the session?'이라고 묻자 Elena(W1)는 'Just a photo ID so we can issue your employee badge.'라고 답합니다. 사원증 발급을 위해 사진이 있는 신분증을 가져오라는 것이므로 정답은 (D)입니다. 계약서, 개인 노트북, 설문지는 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0022",
    "part": 3,
    "type": "LC",
    "question": "Why is the woman calling the help desk?",
    "script": "W: Hi, this is Mira in the sales department. My computer keeps freezing whenever I open the customer database, and I have to submit a sales report by noon. M: I see. Have you tried restarting your computer? That sometimes clears the issue. W: Yes, I've restarted it twice already, but the problem keeps happening. M: In that case, it might be related to the database update we ran last night. A few other users have reported the same thing. W: Is there a way I can access my data in the meantime? My deadline is in two hours. M: You can log in to the database through the web portal instead of the desktop program. I'll send you the link, and we'll have the desktop issue fixed by the end of the day.",
    "options": [
      "Her computer keeps freezing",
      "She forgot her login password",
      "Her sales report was deleted",
      "Her monitor screen is cracked"
    ],
    "answer": 0,
    "explanation": "여자는 첫 대사에서 'My computer keeps freezing whenever I open the customer database'라고 말하며 고객 데이터베이스를 열 때마다 컴퓨터가 멈춘다는 문제를 알리고 있습니다. 따라서 정답은 (A)입니다. 비밀번호 분실, 보고서 삭제, 모니터 파손은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0023",
    "part": 3,
    "type": "LC",
    "question": "What does the man say caused the problem?",
    "script": "W: Hi, this is Mira in the sales department. My computer keeps freezing whenever I open the customer database, and I have to submit a sales report by noon. M: I see. Have you tried restarting your computer? That sometimes clears the issue. W: Yes, I've restarted it twice already, but the problem keeps happening. M: In that case, it might be related to the database update we ran last night. A few other users have reported the same thing. W: Is there a way I can access my data in the meantime? My deadline is in two hours. M: You can log in to the database through the web portal instead of the desktop program. I'll send you the link, and we'll have the desktop issue fixed by the end of the day.",
    "options": [
      "A power outage in the building",
      "A recent database update",
      "An expired software license",
      "A computer virus"
    ],
    "answer": 1,
    "explanation": "남자는 'it might be related to the database update we ran last night. A few other users have reported the same thing.'이라고 말하며 지난밤 실행한 데이터베이스 업데이트가 원인일 수 있다고 설명합니다. 따라서 정답은 (B)입니다. 정전, 라이선스 만료, 바이러스는 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0024",
    "part": 3,
    "type": "LC",
    "question": "What solution does the man offer the woman?",
    "script": "W: Hi, this is Mira in the sales department. My computer keeps freezing whenever I open the customer database, and I have to submit a sales report by noon. M: I see. Have you tried restarting your computer? That sometimes clears the issue. W: Yes, I've restarted it twice already, but the problem keeps happening. M: In that case, it might be related to the database update we ran last night. A few other users have reported the same thing. W: Is there a way I can access my data in the meantime? My deadline is in two hours. M: You can log in to the database through the web portal instead of the desktop program. I'll send you the link, and we'll have the desktop issue fixed by the end of the day.",
    "options": [
      "Extending her report deadline",
      "Replacing her computer with a new one",
      "Accessing the database through a web portal",
      "Sending her report on her behalf"
    ],
    "answer": 2,
    "explanation": "남자는 마지막 대사에서 'You can log in to the database through the web portal instead of the desktop program. I'll send you the link'라고 말하며 데스크톱 프로그램 대신 웹 포털로 데이터베이스에 접속하는 임시 해결책을 제시합니다. 따라서 정답은 (C)입니다. 마감 연장, 컴퓨터 교체, 대리 제출은 제안되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0025",
    "part": 3,
    "type": "LC",
    "question": "What are the speakers mainly discussing?",
    "script": "M: Sandra, we need to finalize the venue for the launch event of our new fitness tracker next month. Have you heard back from the Grandview Hall? W: Yes, unfortunately they're booked solid through the end of next month. But the Lakeside Pavilion is available on the fifteenth, and it can hold up to three hundred guests. M: The Pavilion has great views, but isn't it a bit expensive? Our event budget was trimmed this quarter. W: Actually, they're offering twenty percent off for weekday bookings. If we hold the event on a Thursday, we'd stay within budget. M: A Thursday could work. Most of the tech journalists we invited are local anyway. W: Then I'll call the Pavilion this afternoon and put down the deposit before someone else takes the date.",
    "options": [
      "Choosing a venue for a product launch",
      "Redesigning a fitness tracker",
      "Inviting more journalists to an event",
      "Increasing the quarterly budget"
    ],
    "answer": 0,
    "explanation": "남자는 첫 대사에서 'we need to finalize the venue for the launch event of our new fitness tracker'라고 말하고, 이후 대화 전체가 Grandview Hall과 Lakeside Pavilion 중 행사 장소를 정하는 내용으로 진행됩니다. 따라서 정답은 (A)입니다. 제품 디자인 변경이나 예산 증액은 논의되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0026",
    "part": 3,
    "type": "LC",
    "question": "What does the woman imply about holding the event on a Thursday?",
    "script": "M: Sandra, we need to finalize the venue for the launch event of our new fitness tracker next month. Have you heard back from the Grandview Hall? W: Yes, unfortunately they're booked solid through the end of next month. But the Lakeside Pavilion is available on the fifteenth, and it can hold up to three hundred guests. M: The Pavilion has great views, but isn't it a bit expensive? Our event budget was trimmed this quarter. W: Actually, they're offering twenty percent off for weekday bookings. If we hold the event on a Thursday, we'd stay within budget. M: A Thursday could work. Most of the tech journalists we invited are local anyway. W: Then I'll call the Pavilion this afternoon and put down the deposit before someone else takes the date.",
    "options": [
      "It would attract more international guests",
      "It would require extending the venue hours",
      "It would conflict with another launch event",
      "It would make the venue affordable"
    ],
    "answer": 3,
    "explanation": "남자가 Pavilion이 비싸지 않냐고 우려하자 여자는 'they're offering twenty percent off for weekday bookings. If we hold the event on a Thursday, we'd stay within budget.'이라고 답합니다. 평일 예약 시 20% 할인이 적용되어 목요일에 행사를 열면 예산 내에서 가능하다는 의미이므로, 목요일 개최가 비용 문제를 해결해 준다는 (D)가 정답입니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0027",
    "part": 3,
    "type": "LC",
    "question": "What does the woman say she will do this afternoon?",
    "script": "M: Sandra, we need to finalize the venue for the launch event of our new fitness tracker next month. Have you heard back from the Grandview Hall? W: Yes, unfortunately they're booked solid through the end of next month. But the Lakeside Pavilion is available on the fifteenth, and it can hold up to three hundred guests. M: The Pavilion has great views, but isn't it a bit expensive? Our event budget was trimmed this quarter. W: Actually, they're offering twenty percent off for weekday bookings. If we hold the event on a Thursday, we'd stay within budget. M: A Thursday could work. Most of the tech journalists we invited are local anyway. W: Then I'll call the Pavilion this afternoon and put down the deposit before someone else takes the date.",
    "options": [
      "Send invitations to journalists",
      "Visit the Grandview Hall",
      "Pay a deposit for a venue",
      "Revise the event budget"
    ],
    "answer": 2,
    "explanation": "여자는 마지막 대사에서 'I'll call the Pavilion this afternoon and put down the deposit before someone else takes the date.'라고 말합니다. 오늘 오후에 Pavilion에 전화해 보증금을 내겠다는 것이므로 정답은 (C)입니다. put down the deposit이 pay a deposit으로 바뀌어 표현되었습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0028",
    "part": 3,
    "type": "LC",
    "question": "Why is the man calling the hotel?",
    "script": "M: Good evening. I have a reservation under the name Okafor for tonight, but my flight has been delayed, and I won't arrive until well after midnight. I wanted to make sure my room won't be given away. W: Thank you for letting us know, Mr. Okafor. I see your reservation here. Since you booked with a credit card guarantee, we'll hold the room no matter how late you arrive. M: That's a relief. One more thing — will the front desk still be open when I get there? W: Yes, our front desk is staffed twenty-four hours a day. However, our restaurant closes at ten, so if you'd like a late meal, I can arrange a cold dinner plate to be left in your room. M: That would be wonderful. Something light would be perfect after such a long day. W: Consider it done. We'll see you tonight, and I hope the rest of your journey goes smoothly.",
    "options": [
      "To cancel his reservation",
      "To inform the hotel of his late arrival",
      "To complain about a room charge",
      "To ask about airport shuttle times"
    ],
    "answer": 1,
    "explanation": "남자는 'my flight has been delayed, and I won't arrive until well after midnight. I wanted to make sure my room won't be given away.'라고 말합니다. 항공편 지연으로 자정 넘어 도착한다는 사실을 호텔에 알리고 객실이 취소되지 않도록 확인하려는 전화이므로 정답은 (B)입니다. 예약 취소나 요금 불만, 셔틀 문의가 아닙니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0029",
    "part": 3,
    "type": "LC",
    "question": "What does the woman say about the front desk?",
    "script": "M: Good evening. I have a reservation under the name Okafor for tonight, but my flight has been delayed, and I won't arrive until well after midnight. I wanted to make sure my room won't be given away. W: Thank you for letting us know, Mr. Okafor. I see your reservation here. Since you booked with a credit card guarantee, we'll hold the room no matter how late you arrive. M: That's a relief. One more thing — will the front desk still be open when I get there? W: Yes, our front desk is staffed twenty-four hours a day. However, our restaurant closes at ten, so if you'd like a late meal, I can arrange a cold dinner plate to be left in your room. M: That would be wonderful. Something light would be perfect after such a long day. W: Consider it done. We'll see you tonight, and I hope the rest of your journey goes smoothly.",
    "options": [
      "It closes at ten p.m.",
      "It is being remodeled",
      "It operates around the clock",
      "It is located on the second floor"
    ],
    "answer": 2,
    "explanation": "여자는 'our front desk is staffed twenty-four hours a day'라고 말합니다. 프런트 데스크가 24시간 운영된다는 의미로, 이를 operates around the clock으로 바꾸어 표현한 (C)가 정답입니다. 10시에 닫는 것은 프런트가 아니라 레스토랑이므로 (A)와 혼동하지 않도록 주의해야 합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0030",
    "part": 3,
    "type": "LC",
    "question": "What does the woman offer to do for the man?",
    "script": "M: Good evening. I have a reservation under the name Okafor for tonight, but my flight has been delayed, and I won't arrive until well after midnight. I wanted to make sure my room won't be given away. W: Thank you for letting us know, Mr. Okafor. I see your reservation here. Since you booked with a credit card guarantee, we'll hold the room no matter how late you arrive. M: That's a relief. One more thing — will the front desk still be open when I get there? W: Yes, our front desk is staffed twenty-four hours a day. However, our restaurant closes at ten, so if you'd like a late meal, I can arrange a cold dinner plate to be left in your room. M: That would be wonderful. Something light would be perfect after such a long day. W: Consider it done. We'll see you tonight, and I hope the rest of your journey goes smoothly.",
    "options": [
      "Upgrade his room for free",
      "Arrange a taxi from the airport",
      "Extend the restaurant's hours",
      "Have a meal placed in his room"
    ],
    "answer": 3,
    "explanation": "여자는 'I can arrange a cold dinner plate to be left in your room.'이라고 제안하고 남자가 이를 수락합니다. 객실에 식사를 준비해 두겠다는 제안이므로 정답은 (D)입니다. 객실 업그레이드, 레스토랑 연장 영업, 택시 수배는 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0031",
    "part": 3,
    "type": "LC",
    "question": "What is the conversation mainly about?",
    "script": "W: Mr. Hong, do you have a minute? I'd like to talk about my annual performance review. M: Of course, Yuna. Come on in. I was actually planning to schedule a meeting with you this week. W: Thank you. I noticed the review mentioned my leadership on the Donovan account, and I was wondering whether that might be considered for the senior consultant opening. M: Your work on that account was excellent, and yes, your name has come up in our discussions. The position requires managing three junior staff members, though. How do you feel about that? W: I actually mentored two interns last summer, and both of them were offered full-time positions afterward. M: That's a strong point in your favor. Submit a formal application by Friday, and I'll add my recommendation to it.",
    "options": [
      "A possible promotion for the woman",
      "A complaint about a coworker",
      "A delay in the Donovan account",
      "A summer internship program"
    ],
    "answer": 0,
    "explanation": "여자는 연례 인사 평가 이야기를 꺼내며 'I was wondering whether that might be considered for the senior consultant opening'이라고 말해 선임 컨설턴트 자리에 지원할 뜻을 내비치고, 남자는 지원서를 내면 추천서를 더해 주겠다고 합니다. 대화 전체가 여자의 승진 가능성에 관한 것이므로 정답은 (A)입니다. 인턴십은 여자의 자격을 뒷받침하는 근거로만 언급됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0032",
    "part": 3,
    "type": "LC",
    "question": "What does the woman mention about the interns she mentored?",
    "script": "W: Mr. Hong, do you have a minute? I'd like to talk about my annual performance review. M: Of course, Yuna. Come on in. I was actually planning to schedule a meeting with you this week. W: Thank you. I noticed the review mentioned my leadership on the Donovan account, and I was wondering whether that might be considered for the senior consultant opening. M: Your work on that account was excellent, and yes, your name has come up in our discussions. The position requires managing three junior staff members, though. How do you feel about that? W: I actually mentored two interns last summer, and both of them were offered full-time positions afterward. M: That's a strong point in your favor. Submit a formal application by Friday, and I'll add my recommendation to it.",
    "options": [
      "They transferred to another branch",
      "They were hired as full-time employees",
      "They worked on the Donovan account",
      "They are applying for the same position"
    ],
    "answer": 1,
    "explanation": "여자는 'I actually mentored two interns last summer, and both of them were offered full-time positions afterward.'라고 말합니다. 자신이 멘토링한 인턴 두 명이 이후 정규직 제안을 받았다는 내용이므로 정답은 (B)입니다. 이는 여자가 부하 직원을 관리할 역량이 있음을 보여 주는 근거로 사용되었습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0033",
    "part": 3,
    "type": "LC",
    "question": "What does the man ask the woman to do by Friday?",
    "script": "W: Mr. Hong, do you have a minute? I'd like to talk about my annual performance review. M: Of course, Yuna. Come on in. I was actually planning to schedule a meeting with you this week. W: Thank you. I noticed the review mentioned my leadership on the Donovan account, and I was wondering whether that might be considered for the senior consultant opening. M: Your work on that account was excellent, and yes, your name has come up in our discussions. The position requires managing three junior staff members, though. How do you feel about that? W: I actually mentored two interns last summer, and both of them were offered full-time positions afterward. M: That's a strong point in your favor. Submit a formal application by Friday, and I'll add my recommendation to it.",
    "options": [
      "Complete a training course",
      "Interview three junior staff members",
      "Finish the Donovan account report",
      "Submit a formal application"
    ],
    "answer": 3,
    "explanation": "남자는 마지막 대사에서 'Submit a formal application by Friday, and I'll add my recommendation to it.'이라고 말합니다. 금요일까지 정식 지원서를 제출하라고 요청하므로 정답은 (D)입니다. 교육 이수, 보고서 작성, 직원 면접은 요청되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0034",
    "part": 3,
    "type": "LC",
    "question": "Who most likely is the man?",
    "script": "M: Thanks for coming in, Ms. Vance. This is the office space I mentioned on the phone — about two hundred square meters on the sixth floor with views of the riverfront. W: It's brighter than I expected. We're a design firm of twelve people, so natural light is important to us. M: Then you'll love the floor-to-ceiling windows on the east side. The lease also includes two reserved parking spots and access to the shared conference center downstairs. W: That's convenient. What's the monthly rent? M: It's four thousand two hundred dollars, utilities included. The current tenant moves out at the end of this month, so the space would be available from the first of August. W: That timing actually suits us. Could you e-mail me a copy of the lease terms? I'd like our lawyer to look them over before we commit.",
    "options": [
      "A real estate agent",
      "An interior designer",
      "A building janitor",
      "A bank loan officer"
    ],
    "answer": 0,
    "explanation": "남자는 사무 공간을 보여 주며 면적, 전망, 임대 조건(주차 2면, 공용 회의 시설), 월 임대료, 입주 가능 시기 등을 안내하고 있습니다. 임대 물건을 중개하는 역할을 하고 있으므로 부동산 중개인인 (A)가 정답입니다. (B) 인테리어 디자이너는 여자의 회사(design firm)와 관련된 함정 선택지입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0035",
    "part": 3,
    "type": "LC",
    "question": "What feature of the office is important to the woman?",
    "script": "M: Thanks for coming in, Ms. Vance. This is the office space I mentioned on the phone — about two hundred square meters on the sixth floor with views of the riverfront. W: It's brighter than I expected. We're a design firm of twelve people, so natural light is important to us. M: Then you'll love the floor-to-ceiling windows on the east side. The lease also includes two reserved parking spots and access to the shared conference center downstairs. W: That's convenient. What's the monthly rent? M: It's four thousand two hundred dollars, utilities included. The current tenant moves out at the end of this month, so the space would be available from the first of August. W: That timing actually suits us. Could you e-mail me a copy of the lease terms? I'd like our lawyer to look them over before we commit.",
    "options": [
      "A private elevator",
      "Natural lighting",
      "A rooftop terrace",
      "Soundproof walls"
    ],
    "answer": 1,
    "explanation": "여자는 'We're a design firm of twelve people, so natural light is important to us.'라고 말합니다. 디자인 회사라서 자연광이 중요하다고 직접 언급하므로 정답은 (B)입니다. 엘리베이터, 옥상 테라스, 방음벽은 대화에서 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0036",
    "part": 3,
    "type": "LC",
    "question": "Why does the woman want a copy of the lease terms?",
    "script": "M: Thanks for coming in, Ms. Vance. This is the office space I mentioned on the phone — about two hundred square meters on the sixth floor with views of the riverfront. W: It's brighter than I expected. We're a design firm of twelve people, so natural light is important to us. M: Then you'll love the floor-to-ceiling windows on the east side. The lease also includes two reserved parking spots and access to the shared conference center downstairs. W: That's convenient. What's the monthly rent? M: It's four thousand two hundred dollars, utilities included. The current tenant moves out at the end of this month, so the space would be available from the first of August. W: That timing actually suits us. Could you e-mail me a copy of the lease terms? I'd like our lawyer to look them over before we commit.",
    "options": [
      "To compare them with another property",
      "To check the parking regulations",
      "To negotiate a lower rent",
      "To have a lawyer review them"
    ],
    "answer": 3,
    "explanation": "여자는 마지막 대사에서 'Could you e-mail me a copy of the lease terms? I'd like our lawyer to look them over before we commit.'라고 말합니다. 계약하기 전에 변호사가 임대 조건을 검토하도록 하기 위해서이므로 정답은 (D)입니다. look over(검토하다)가 review로 바뀌어 표현되었습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0037",
    "part": 3,
    "type": "LC",
    "question": "What problem are the speakers discussing?",
    "script": "M1: Karen, Jeff, thanks for joining on short notice. The shipment for the Hailford order was supposed to arrive at their warehouse yesterday, but it's still sitting at the port. W: I just spoke with the freight company. There's a customs documentation issue — apparently one of the certificates we submitted had an outdated form number. M2: That's the second time this quarter. Last time it delayed the Meridian order by a full week. M1: We can't let that happen again. Hailford is our biggest client in that region. W: The freight company says if we submit the corrected certificate by five p.m. today, the shipment can clear customs tomorrow morning. M2: I have the updated template on my computer. I can prepare the corrected document within the hour. M1: Perfect, Jeff. Karen, once he's done, please send it directly to the customs broker and copy me on the e-mail.",
    "options": [
      "A delayed shipment",
      "A damaged warehouse",
      "A canceled client contract",
      "A staff shortage at the port"
    ],
    "answer": 0,
    "explanation": "첫 화자(M1)는 'The shipment for the Hailford order was supposed to arrive at their warehouse yesterday, but it's still sitting at the port.'라고 말합니다. 어제 도착했어야 할 화물이 아직 항구에 묶여 있다는 배송 지연 문제를 논의하고 있으므로 정답은 (A)입니다. 창고 파손, 계약 취소, 인력 부족은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0038",
    "part": 3,
    "type": "LC",
    "question": "According to the woman, what caused the delay?",
    "script": "M1: Karen, Jeff, thanks for joining on short notice. The shipment for the Hailford order was supposed to arrive at their warehouse yesterday, but it's still sitting at the port. W: I just spoke with the freight company. There's a customs documentation issue — apparently one of the certificates we submitted had an outdated form number. M2: That's the second time this quarter. Last time it delayed the Meridian order by a full week. M1: We can't let that happen again. Hailford is our biggest client in that region. W: The freight company says if we submit the corrected certificate by five p.m. today, the shipment can clear customs tomorrow morning. M2: I have the updated template on my computer. I can prepare the corrected document within the hour. M1: Perfect, Jeff. Karen, once he's done, please send it directly to the customs broker and copy me on the e-mail.",
    "options": [
      "A vessel arrived behind schedule",
      "A certificate had an outdated form number",
      "A warehouse was over capacity",
      "A payment was not processed on time"
    ],
    "answer": 1,
    "explanation": "여자는 'There's a customs documentation issue — apparently one of the certificates we submitted had an outdated form number.'라고 말합니다. 제출한 증명서 중 하나에 구버전 양식 번호가 있어 통관 서류 문제가 생겼다는 것이므로 정답은 (B)입니다. 선박 지연, 창고 문제, 결제 문제는 언급되지 않았습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0039",
    "part": 3,
    "type": "LC",
    "question": "What is Karen asked to do?",
    "script": "M1: Karen, Jeff, thanks for joining on short notice. The shipment for the Hailford order was supposed to arrive at their warehouse yesterday, but it's still sitting at the port. W: I just spoke with the freight company. There's a customs documentation issue — apparently one of the certificates we submitted had an outdated form number. M2: That's the second time this quarter. Last time it delayed the Meridian order by a full week. M1: We can't let that happen again. Hailford is our biggest client in that region. W: The freight company says if we submit the corrected certificate by five p.m. today, the shipment can clear customs tomorrow morning. M2: I have the updated template on my computer. I can prepare the corrected document within the hour. M1: Perfect, Jeff. Karen, once he's done, please send it directly to the customs broker and copy me on the e-mail.",
    "options": [
      "Prepare a corrected certificate",
      "Call the Hailford warehouse",
      "Send a document to the customs broker",
      "Negotiate with the freight company"
    ],
    "answer": 2,
    "explanation": "M1은 마지막 대사에서 'Karen, once he's done, please send it directly to the customs broker and copy me on the e-mail.'이라고 지시합니다. Jeff가 수정 서류를 작성하면 Karen이 그것을 관세사에게 보내야 하므로 정답은 (C)입니다. (A) 수정 증명서 작성은 Jeff(M2)의 역할이므로, 3인 대화에서 누구에게 어떤 일이 배정되었는지 구분해야 합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0040",
    "part": 3,
    "type": "LC",
    "question": "What is the main purpose of the meeting?",
    "script": "W: Before we wrap up, let's go over the travel budget for next quarter. Finance has asked every department to cut expenses by ten percent. M: That's going to be difficult. We already have four client visits scheduled, and two of them are overseas. W: I know. One option is to switch the domestic trips to video conferences. The Atlanta client has already said they're comfortable meeting online. M: That would save us around three thousand dollars in flights and hotels. But the Tokyo visit has to stay in person — we're signing the contract renewal there. W: Agreed. Let's keep both overseas trips and make the two domestic meetings virtual. That should get us close to the ten percent target. M: I'll rework the numbers this afternoon and send you the revised budget before I leave today.",
    "options": [
      "To plan a client appreciation event",
      "To prepare for a contract negotiation",
      "To choose a new video conference system",
      "To discuss reducing travel expenses"
    ],
    "answer": 3,
    "explanation": "여자는 'let's go over the travel budget for next quarter. Finance has asked every department to cut expenses by ten percent.'라고 말하며 출장 경비 10% 절감 방안을 논의하기 시작합니다. 대화 전체가 출장비 절감 방법(국내 출장의 화상회의 전환 등)에 관한 것이므로 정답은 (D)입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0041",
    "part": 3,
    "type": "LC",
    "question": "Why does the man say the Tokyo visit must remain in person?",
    "script": "W: Before we wrap up, let's go over the travel budget for next quarter. Finance has asked every department to cut expenses by ten percent. M: That's going to be difficult. We already have four client visits scheduled, and two of them are overseas. W: I know. One option is to switch the domestic trips to video conferences. The Atlanta client has already said they're comfortable meeting online. M: That would save us around three thousand dollars in flights and hotels. But the Tokyo visit has to stay in person — we're signing the contract renewal there. W: Agreed. Let's keep both overseas trips and make the two domestic meetings virtual. That should get us close to the ten percent target. M: I'll rework the numbers this afternoon and send you the revised budget before I leave today.",
    "options": [
      "A contract will be signed there",
      "The client refuses to meet online",
      "The flight tickets are nonrefundable",
      "A factory tour is included in the visit"
    ],
    "answer": 0,
    "explanation": "남자는 'But the Tokyo visit has to stay in person — we're signing the contract renewal there.'라고 말합니다. 도쿄에서 계약 갱신에 서명할 예정이기 때문에 대면 방문이 필요하다는 것이므로 정답은 (A)입니다. 고객의 거부나 항공권 환불 문제, 공장 견학은 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0042",
    "part": 3,
    "type": "LC",
    "question": "What will the man do before leaving today?",
    "script": "W: Before we wrap up, let's go over the travel budget for next quarter. Finance has asked every department to cut expenses by ten percent. M: That's going to be difficult. We already have four client visits scheduled, and two of them are overseas. W: I know. One option is to switch the domestic trips to video conferences. The Atlanta client has already said they're comfortable meeting online. M: That would save us around three thousand dollars in flights and hotels. But the Tokyo visit has to stay in person — we're signing the contract renewal there. W: Agreed. Let's keep both overseas trips and make the two domestic meetings virtual. That should get us close to the ten percent target. M: I'll rework the numbers this afternoon and send you the revised budget before I leave today.",
    "options": [
      "Book flights to Tokyo",
      "Call the Atlanta client",
      "Send a revised budget",
      "Schedule a video conference"
    ],
    "answer": 2,
    "explanation": "남자는 마지막 대사에서 'I'll rework the numbers this afternoon and send you the revised budget before I leave today.'라고 말합니다. 퇴근 전에 수정된 예산안을 보내겠다는 것이므로 정답은 (C)입니다. 항공권 예약, 고객 전화, 화상회의 일정 잡기는 오늘 할 일로 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0043",
    "part": 3,
    "type": "LC",
    "question": "Where do the speakers most likely work?",
    "script": "M1: Excuse me, do you two have a moment? A customer just asked when the autumn jackets will be back in the medium size. The rack on the main floor is empty. W: I checked the stockroom this morning — we're completely out of mediums. The new delivery isn't due until Thursday. M2: Actually, the Westgate store called earlier. They're overstocked on that exact jacket and offered to transfer some to us. W: Really? How many can they send? M2: About twenty, in assorted sizes including medium. If we confirm by three o'clock, the boxes will arrive on tomorrow's van. M1: Let's confirm right away. And could one of you put up a notice at the register telling customers the jackets will be available tomorrow? W: I'll take care of the notice as soon as we call Westgate back.",
    "options": [
      "At a clothing store",
      "At a dry cleaner",
      "At a shipping warehouse",
      "At a tailor's shop"
    ],
    "answer": 0,
    "explanation": "대화에서 autumn jackets(가을 재킷), medium size, rack(진열대), stockroom(재고 창고), register(계산대) 등 의류 매장과 관련된 표현이 계속 등장하고, 고객 문의에 대응하는 상황이므로 화자들은 옷 가게에서 일한다고 볼 수 있습니다. 정답은 (A)입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0044",
    "part": 3,
    "type": "LC",
    "question": "What does the second man say about the Westgate store?",
    "script": "M1: Excuse me, do you two have a moment? A customer just asked when the autumn jackets will be back in the medium size. The rack on the main floor is empty. W: I checked the stockroom this morning — we're completely out of mediums. The new delivery isn't due until Thursday. M2: Actually, the Westgate store called earlier. They're overstocked on that exact jacket and offered to transfer some to us. W: Really? How many can they send? M2: About twenty, in assorted sizes including medium. If we confirm by three o'clock, the boxes will arrive on tomorrow's van. M1: Let's confirm right away. And could one of you put up a notice at the register telling customers the jackets will be available tomorrow? W: I'll take care of the notice as soon as we call Westgate back.",
    "options": [
      "It is closing down next month",
      "It has extra stock of the jackets",
      "It needs to borrow some staff",
      "It is holding a clearance sale"
    ],
    "answer": 1,
    "explanation": "두 번째 남자(M2)는 'the Westgate store called earlier. They're overstocked on that exact jacket and offered to transfer some to us.'라고 말합니다. Westgate 매장에 해당 재킷의 재고가 남아돌아 일부를 보내 주겠다고 제안했다는 것이므로, overstocked를 has extra stock으로 바꾸어 표현한 (B)가 정답입니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0045",
    "part": 3,
    "type": "LC",
    "question": "What will the woman do after calling the Westgate store?",
    "script": "M1: Excuse me, do you two have a moment? A customer just asked when the autumn jackets will be back in the medium size. The rack on the main floor is empty. W: I checked the stockroom this morning — we're completely out of mediums. The new delivery isn't due until Thursday. M2: Actually, the Westgate store called earlier. They're overstocked on that exact jacket and offered to transfer some to us. W: Really? How many can they send? M2: About twenty, in assorted sizes including medium. If we confirm by three o'clock, the boxes will arrive on tomorrow's van. M1: Let's confirm right away. And could one of you put up a notice at the register telling customers the jackets will be available tomorrow? W: I'll take care of the notice as soon as we call Westgate back.",
    "options": [
      "Unload boxes from a delivery van",
      "Offer the customer a discount",
      "Reorganize the stockroom",
      "Post a notice at the register"
    ],
    "answer": 3,
    "explanation": "M1이 계산대에 재킷 입고 안내문을 붙여 달라고 부탁하자 여자는 'I'll take care of the notice as soon as we call Westgate back.'이라고 답합니다. Westgate에 전화한 뒤 안내문을 붙이겠다는 것이므로 정답은 (D)입니다. 배송 상자 하역이나 창고 정리, 할인 제공은 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0046",
    "part": 3,
    "type": "LC",
    "question": "What did the woman's team recently do?",
    "script": "W: Daniel, my team just finished analyzing the customer satisfaction survey from last month. Over two thousand customers responded. M: That's a great response rate. What were the main findings? W: Overall satisfaction is up, but there's one recurring complaint — customers say our delivery window is too vague. They want an exact time, not just a morning or afternoon slot. M: Interesting. Our competitor started offering one-hour delivery windows last year. Maybe that's raising expectations. W: Exactly. I think we should present this to the operations team and propose a pilot program with narrower delivery windows in one region. M: Good plan. The operations director will want cost estimates, though. Can your team prepare some figures before the presentation? W: Sure. We'll have a cost analysis ready by early next week.",
    "options": [
      "Conducted interviews with competitors",
      "Analyzed a customer survey",
      "Launched a new delivery service",
      "Reorganized the operations team"
    ],
    "answer": 1,
    "explanation": "여자는 첫 대사에서 'my team just finished analyzing the customer satisfaction survey from last month'라고 말합니다. 여자의 팀이 최근에 한 일은 고객 만족도 설문 분석이므로 정답은 (B)입니다. 경쟁사 인터뷰, 배송 서비스 출시, 조직 개편은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0047",
    "part": 3,
    "type": "LC",
    "question": "What complaint did customers make?",
    "script": "W: Daniel, my team just finished analyzing the customer satisfaction survey from last month. Over two thousand customers responded. M: That's a great response rate. What were the main findings? W: Overall satisfaction is up, but there's one recurring complaint — customers say our delivery window is too vague. They want an exact time, not just a morning or afternoon slot. M: Interesting. Our competitor started offering one-hour delivery windows last year. Maybe that's raising expectations. W: Exactly. I think we should present this to the operations team and propose a pilot program with narrower delivery windows in one region. M: Good plan. The operations director will want cost estimates, though. Can your team prepare some figures before the presentation? W: Sure. We'll have a cost analysis ready by early next week.",
    "options": [
      "Delivery times are not specific enough",
      "Products often arrive damaged",
      "Customer service is hard to reach",
      "Prices are higher than competitors'"
    ],
    "answer": 0,
    "explanation": "여자는 'customers say our delivery window is too vague. They want an exact time, not just a morning or afternoon slot.'이라고 말합니다. 배송 시간대가 너무 모호하다는 것이 반복적인 불만이므로, 이를 not specific enough로 바꾸어 표현한 (A)가 정답입니다. 파손, 고객센터 연결, 가격 불만은 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0048",
    "part": 3,
    "type": "LC",
    "question": "What will the woman's team prepare by early next week?",
    "script": "W: Daniel, my team just finished analyzing the customer satisfaction survey from last month. Over two thousand customers responded. M: That's a great response rate. What were the main findings? W: Overall satisfaction is up, but there's one recurring complaint — customers say our delivery window is too vague. They want an exact time, not just a morning or afternoon slot. M: Interesting. Our competitor started offering one-hour delivery windows last year. Maybe that's raising expectations. W: Exactly. I think we should present this to the operations team and propose a pilot program with narrower delivery windows in one region. M: Good plan. The operations director will want cost estimates, though. Can your team prepare some figures before the presentation? W: Sure. We'll have a cost analysis ready by early next week.",
    "options": [
      "A new survey questionnaire",
      "A press release",
      "A regional delivery map",
      "A cost analysis"
    ],
    "answer": 3,
    "explanation": "남자가 운영 이사가 비용 추정치를 원할 것이라며 수치를 준비해 달라고 하자, 여자는 'We'll have a cost analysis ready by early next week.'라고 답합니다. 다음 주 초까지 비용 분석 자료를 준비하겠다는 것이므로 정답은 (D)입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0049",
    "part": 3,
    "type": "LC",
    "question": "What announcement is the man explaining?",
    "script": "M: Hi Olivia, did you get the notice about the parking garage? Starting next Monday, the lower two levels will be closed for about six weeks for structural repairs. W: Six weeks? Where are we supposed to park during that time? The upper levels barely fit half of us. M: The company arranged temporary spots at the municipal lot on Granger Street. It's about a ten-minute walk from our building. W: That's quite a walk in the summer heat. Will the company cover the parking fees there? M: Yes, just show your employee badge at the booth, and the fee is billed directly to the company. They're also adding a morning shuttle that loops between the lot and our entrance every fifteen minutes. W: A shuttle would help. I'll forward this information to my team since a few of them missed the notice.",
    "options": [
      "A temporary closure of a parking area",
      "A change in building security policy",
      "A new public transportation subsidy",
      "An extension of office hours"
    ],
    "answer": 0,
    "explanation": "남자는 'Starting next Monday, the lower two levels will be closed for about six weeks for structural repairs.'라고 말하며 주차장 하부 2개 층이 구조 보수 공사로 약 6주간 폐쇄된다는 공지를 설명합니다. 따라서 정답은 (A)입니다. 보안 정책, 교통비 지원 제도, 근무 시간 연장은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0050",
    "part": 3,
    "type": "LC",
    "question": "How can employees avoid paying at the municipal lot?",
    "script": "M: Hi Olivia, did you get the notice about the parking garage? Starting next Monday, the lower two levels will be closed for about six weeks for structural repairs. W: Six weeks? Where are we supposed to park during that time? The upper levels barely fit half of us. M: The company arranged temporary spots at the municipal lot on Granger Street. It's about a ten-minute walk from our building. W: That's quite a walk in the summer heat. Will the company cover the parking fees there? M: Yes, just show your employee badge at the booth, and the fee is billed directly to the company. They're also adding a morning shuttle that loops between the lot and our entrance every fifteen minutes. W: A shuttle would help. I'll forward this information to my team since a few of them missed the notice.",
    "options": [
      "By registering their license plates online",
      "By showing their employee badges",
      "By submitting receipts for reimbursement",
      "By parking before eight a.m."
    ],
    "answer": 1,
    "explanation": "남자는 'just show your employee badge at the booth, and the fee is billed directly to the company'라고 말합니다. 부스에서 사원증을 제시하면 요금이 회사로 직접 청구된다는 것이므로 정답은 (B)입니다. 차량 등록, 영수증 제출 후 환급, 이른 주차는 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0051",
    "part": 3,
    "type": "LC",
    "question": "What does the woman say she will do?",
    "script": "M: Hi Olivia, did you get the notice about the parking garage? Starting next Monday, the lower two levels will be closed for about six weeks for structural repairs. W: Six weeks? Where are we supposed to park during that time? The upper levels barely fit half of us. M: The company arranged temporary spots at the municipal lot on Granger Street. It's about a ten-minute walk from our building. W: That's quite a walk in the summer heat. Will the company cover the parking fees there? M: Yes, just show your employee badge at the booth, and the fee is billed directly to the company. They're also adding a morning shuttle that loops between the lot and our entrance every fifteen minutes. W: A shuttle would help. I'll forward this information to my team since a few of them missed the notice.",
    "options": [
      "Park on the upper levels",
      "Take the shuttle tomorrow morning",
      "Share the information with her team",
      "Complain to the facilities department"
    ],
    "answer": 2,
    "explanation": "여자는 마지막 대사에서 'I'll forward this information to my team since a few of them missed the notice.'라고 말합니다. 공지를 못 본 팀원들에게 정보를 전달하겠다는 것이므로, forward를 share로 바꾸어 표현한 (C)가 정답입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0052",
    "part": 3,
    "type": "LC",
    "question": "What is the purpose of the training session being discussed?",
    "script": "W1: Thanks for meeting with us, Raj. As you know, the company is switching to the new expense reporting software at the end of the month. M: Right. I've been asked to run the training sessions for all departments. How many sessions are we planning? W2: We were thinking three sessions of about forty people each. The accounting team should go first since they'll be helping other staff afterward. M: That makes sense. Will the sessions be in person or online? W1: In person for accounting, since they need hands-on practice with the approval features. The other two sessions can be webinars. W2: Also, Raj, could you record one of the webinars? Staff who are on leave that week could watch it when they return. M: No problem. I'll set up the recording and upload it to the training portal afterward.",
    "options": [
      "To introduce new expense reporting software",
      "To explain updated security procedures",
      "To onboard newly hired accountants",
      "To demonstrate a video conferencing tool"
    ],
    "answer": 0,
    "explanation": "첫 번째 여자(W1)는 'the company is switching to the new expense reporting software at the end of the month'라고 말하고, 남자가 그 교육 세션 진행을 맡았다고 합니다. 교육의 목적은 새 경비 보고 소프트웨어 도입이므로 정답은 (A)입니다. 보안 절차나 신입 회계사 온보딩, 화상회의 도구 시연이 아닙니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0053",
    "part": 3,
    "type": "LC",
    "question": "Why should the accounting team attend the first session?",
    "script": "W1: Thanks for meeting with us, Raj. As you know, the company is switching to the new expense reporting software at the end of the month. M: Right. I've been asked to run the training sessions for all departments. How many sessions are we planning? W2: We were thinking three sessions of about forty people each. The accounting team should go first since they'll be helping other staff afterward. M: That makes sense. Will the sessions be in person or online? W1: In person for accounting, since they need hands-on practice with the approval features. The other two sessions can be webinars. W2: Also, Raj, could you record one of the webinars? Staff who are on leave that week could watch it when they return. M: No problem. I'll set up the recording and upload it to the training portal afterward.",
    "options": [
      "They requested the earliest time slot",
      "Their busy season starts next month",
      "They are the largest department",
      "They will assist other employees later"
    ],
    "answer": 3,
    "explanation": "두 번째 여자(W2)는 'The accounting team should go first since they'll be helping other staff afterward.'라고 말합니다. 회계팀이 이후 다른 직원들을 도와줄 예정이므로 가장 먼저 교육을 받아야 한다는 것입니다. 따라서 정답은 (D)입니다. 3인 대화에서 발언자별 정보를 정확히 구분해야 하는 문제입니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0054",
    "part": 3,
    "type": "LC",
    "question": "What is the man asked to do with one of the webinars?",
    "script": "W1: Thanks for meeting with us, Raj. As you know, the company is switching to the new expense reporting software at the end of the month. M: Right. I've been asked to run the training sessions for all departments. How many sessions are we planning? W2: We were thinking three sessions of about forty people each. The accounting team should go first since they'll be helping other staff afterward. M: That makes sense. Will the sessions be in person or online? W1: In person for accounting, since they need hands-on practice with the approval features. The other two sessions can be webinars. W2: Also, Raj, could you record one of the webinars? Staff who are on leave that week could watch it when they return. M: No problem. I'll set up the recording and upload it to the training portal afterward.",
    "options": [
      "Translate it into other languages",
      "Shorten it to thirty minutes",
      "Record it for absent staff",
      "Present it to the executives first"
    ],
    "answer": 2,
    "explanation": "W2는 'could you record one of the webinars? Staff who are on leave that week could watch it when they return.'이라고 요청합니다. 휴가 중인 직원들이 나중에 볼 수 있도록 웨비나 하나를 녹화해 달라는 것이므로 정답은 (C)입니다. 남자도 녹화 후 교육 포털에 올리겠다고 답합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0055",
    "part": 3,
    "type": "LC",
    "question": "What are the speakers mainly discussing?",
    "script": "M: Hey Lucia, have you tried the cafeteria since the new vendor took over this week? W: Not yet. I heard they changed the whole menu. How is it? M: Much better, actually. There's a salad bar now, and they added several vegetarian options. The grilled vegetable wrap I had today was excellent. W: That's good to hear. The old menu was getting repetitive. What about the prices, though? M: Slightly higher — about a dollar more per meal on average. But employees get a fifteen percent discount if they pay with their badge instead of cash. W: Oh, I didn't know our badges could do that. I'll have to set that up. Do you know how? M: Just link your badge to a payment card on the employee portal. It took me less than five minutes.",
    "options": [
      "Changes to the company cafeteria",
      "A cooking class for employees",
      "The opening of a nearby restaurant",
      "A healthy eating campaign"
    ],
    "answer": 0,
    "explanation": "남자는 'have you tried the cafeteria since the new vendor took over this week?'라고 물으며 새 업체가 운영을 맡은 구내식당에 대해 이야기를 시작하고, 새 메뉴와 가격, 직원 할인 등 식당의 변화에 관한 내용이 이어집니다. 따라서 정답은 (A)입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0056",
    "part": 3,
    "type": "LC",
    "question": "What does the man imply about paying with an employee badge?",
    "script": "M: Hey Lucia, have you tried the cafeteria since the new vendor took over this week? W: Not yet. I heard they changed the whole menu. How is it? M: Much better, actually. There's a salad bar now, and they added several vegetarian options. The grilled vegetable wrap I had today was excellent. W: That's good to hear. The old menu was getting repetitive. What about the prices, though? M: Slightly higher — about a dollar more per meal on average. But employees get a fifteen percent discount if they pay with their badge instead of cash. W: Oh, I didn't know our badges could do that. I'll have to set that up. Do you know how? M: Just link your badge to a payment card on the employee portal. It took me less than five minutes.",
    "options": [
      "It is only available to managers",
      "It can make meals cheaper than before",
      "It requires approval from the finance team",
      "It is slower than paying with cash"
    ],
    "answer": 1,
    "explanation": "남자는 식사 가격이 평균 1달러 정도 올랐지만 'employees get a fifteen percent discount if they pay with their badge instead of cash'라고 말합니다. 사원증으로 결제하면 15% 할인을 받으므로 결과적으로 식사를 더 저렴하게 할 수 있다는 의미를 내포합니다. 따라서 정답은 (B)입니다. 의도 파악(imply) 유형으로, 직접 언급되지 않은 내용을 추론해야 합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0057",
    "part": 3,
    "type": "LC",
    "question": "According to the man, how can the woman set up badge payments?",
    "script": "M: Hey Lucia, have you tried the cafeteria since the new vendor took over this week? W: Not yet. I heard they changed the whole menu. How is it? M: Much better, actually. There's a salad bar now, and they added several vegetarian options. The grilled vegetable wrap I had today was excellent. W: That's good to hear. The old menu was getting repetitive. What about the prices, though? M: Slightly higher — about a dollar more per meal on average. But employees get a fifteen percent discount if they pay with their badge instead of cash. W: Oh, I didn't know our badges could do that. I'll have to set that up. Do you know how? M: Just link your badge to a payment card on the employee portal. It took me less than five minutes.",
    "options": [
      "By visiting the cafeteria office",
      "By calling the security desk",
      "By linking her badge on the employee portal",
      "By filling out a paper form at reception"
    ],
    "answer": 2,
    "explanation": "남자는 마지막 대사에서 'Just link your badge to a payment card on the employee portal. It took me less than five minutes.'라고 설명합니다. 직원 포털에서 사원증을 결제 카드에 연동하면 된다는 것이므로 정답은 (C)입니다. 식당 사무실 방문, 보안 데스크 전화, 종이 양식 작성은 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0058",
    "part": 3,
    "type": "LC",
    "question": "Where does the woman most likely work?",
    "script": "W: Thank you for calling Beaumont Office Supplies. This is Renata. How can I help you today? M: Hi, I placed order number 4-7-2-9 last Tuesday for twenty boxes of printer paper and five toner cartridges, but only the paper arrived this morning. W: I'm sorry about that. Let me look up your order. Ah, I see — the toner cartridges were on back order, so they were shipped separately from a different warehouse. M: Nobody mentioned that when I ordered. We're nearly out of toner, and we print contracts every day. W: I apologize for the inconvenience. The tracking shows they'll be delivered by Wednesday. If that's too late, I can have two cartridges sent by express courier today at no extra cost. M: Yes, please do that. Two will hold us over until the rest arrive. W: Done. You'll receive the express package before five p.m. today, and I'll e-mail you the tracking numbers for both shipments.",
    "options": [
      "At an office supply company",
      "At a printing shop",
      "At a law firm",
      "At a courier service"
    ],
    "answer": 0,
    "explanation": "여자는 전화를 받으며 'Thank you for calling Beaumont Office Supplies.'라고 인사합니다. 사무용품 회사의 고객 서비스 담당자로서 주문 조회와 배송 처리를 하고 있으므로 정답은 (A)입니다. 인쇄소, 법률 사무소, 택배 회사는 여자의 근무처가 아닙니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0059",
    "part": 3,
    "type": "LC",
    "question": "Why were the toner cartridges not delivered with the paper?",
    "script": "W: Thank you for calling Beaumont Office Supplies. This is Renata. How can I help you today? M: Hi, I placed order number 4-7-2-9 last Tuesday for twenty boxes of printer paper and five toner cartridges, but only the paper arrived this morning. W: I'm sorry about that. Let me look up your order. Ah, I see — the toner cartridges were on back order, so they were shipped separately from a different warehouse. M: Nobody mentioned that when I ordered. We're nearly out of toner, and we print contracts every day. W: I apologize for the inconvenience. The tracking shows they'll be delivered by Wednesday. If that's too late, I can have two cartridges sent by express courier today at no extra cost. M: Yes, please do that. Two will hold us over until the rest arrive. W: Done. You'll receive the express package before five p.m. today, and I'll e-mail you the tracking numbers for both shipments.",
    "options": [
      "They were damaged during packing",
      "The order was accidentally canceled",
      "The delivery address was incorrect",
      "They were on back order"
    ],
    "answer": 3,
    "explanation": "여자는 주문을 조회한 뒤 'the toner cartridges were on back order, so they were shipped separately from a different warehouse'라고 설명합니다. 토너 카트리지가 이월 주문(재고 부족 상태) 상품이어서 다른 창고에서 별도 배송되었다는 것이므로 정답은 (D)입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0060",
    "part": 3,
    "type": "LC",
    "question": "What does the woman offer to do at no extra cost?",
    "script": "W: Thank you for calling Beaumont Office Supplies. This is Renata. How can I help you today? M: Hi, I placed order number 4-7-2-9 last Tuesday for twenty boxes of printer paper and five toner cartridges, but only the paper arrived this morning. W: I'm sorry about that. Let me look up your order. Ah, I see — the toner cartridges were on back order, so they were shipped separately from a different warehouse. M: Nobody mentioned that when I ordered. We're nearly out of toner, and we print contracts every day. W: I apologize for the inconvenience. The tracking shows they'll be delivered by Wednesday. If that's too late, I can have two cartridges sent by express courier today at no extra cost. M: Yes, please do that. Two will hold us over until the rest arrive. W: Done. You'll receive the express package before five p.m. today, and I'll e-mail you the tracking numbers for both shipments.",
    "options": [
      "Refund the entire order",
      "Send some items by express courier",
      "Upgrade his account membership",
      "Include extra boxes of paper"
    ],
    "answer": 1,
    "explanation": "여자는 'I can have two cartridges sent by express courier today at no extra cost.'라고 제안합니다. 추가 비용 없이 카트리지 2개를 오늘 특급 배송으로 보내 주겠다는 것이므로 정답은 (B)입니다. 전액 환불, 멤버십 업그레이드, 추가 용지 제공은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0061",
    "part": 3,
    "type": "LC",
    "question": "What event are the speakers organizing?",
    "script": "W: Min-jun, we should finalize the details for the company health fair next month. The wellness committee wants it bigger than last year. M: Agreed. Last year we only had the flu shot station and a nutrition booth. What are we adding this time? W: I've booked a physical therapist to do posture assessments, and a local gym is sending trainers for a stretching demonstration. M: Excellent. What about the format? Last year's two-hour window was too short — a lot of people couldn't attend because of meetings. W: That's why we're running it from ten a.m. to three p.m. this time, and managers have been asked to let staff attend in shifts. M: Smart. I'll handle the room reservations and ask the cafeteria to set up a healthy snack table. W: Thanks. Once everything is confirmed, I'll design a flyer and post it in the elevators and on the intranet.",
    "options": [
      "A retirement celebration",
      "A medical conference",
      "A charity sports tournament",
      "A company health fair"
    ],
    "answer": 3,
    "explanation": "여자는 첫 대사에서 'we should finalize the details for the company health fair next month'라고 말하고, 이후 독감 예방주사, 자세 평가, 스트레칭 시연 등 사내 건강 박람회의 세부 사항을 논의합니다. 따라서 정답은 (D)입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0062",
    "part": 3,
    "type": "LC",
    "question": "What was the problem with last year's event?",
    "script": "W: Min-jun, we should finalize the details for the company health fair next month. The wellness committee wants it bigger than last year. M: Agreed. Last year we only had the flu shot station and a nutrition booth. What are we adding this time? W: I've booked a physical therapist to do posture assessments, and a local gym is sending trainers for a stretching demonstration. M: Excellent. What about the format? Last year's two-hour window was too short — a lot of people couldn't attend because of meetings. W: That's why we're running it from ten a.m. to three p.m. this time, and managers have been asked to let staff attend in shifts. M: Smart. I'll handle the room reservations and ask the cafeteria to set up a healthy snack table. W: Thanks. Once everything is confirmed, I'll design a flyer and post it in the elevators and on the intranet.",
    "options": [
      "The venue was too small",
      "The time window was too short",
      "The budget was exceeded",
      "Few vendors participated"
    ],
    "answer": 1,
    "explanation": "남자는 'Last year's two-hour window was too short — a lot of people couldn't attend because of meetings.'라고 말합니다. 작년 행사는 2시간으로 너무 짧아 회의 때문에 참석하지 못한 직원이 많았다는 것이 문제였으므로 정답은 (B)입니다. 장소 크기, 예산 초과, 참여 업체 부족은 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0063",
    "part": 3,
    "type": "LC",
    "question": "What will the woman do once everything is confirmed?",
    "script": "W: Min-jun, we should finalize the details for the company health fair next month. The wellness committee wants it bigger than last year. M: Agreed. Last year we only had the flu shot station and a nutrition booth. What are we adding this time? W: I've booked a physical therapist to do posture assessments, and a local gym is sending trainers for a stretching demonstration. M: Excellent. What about the format? Last year's two-hour window was too short — a lot of people couldn't attend because of meetings. W: That's why we're running it from ten a.m. to three p.m. this time, and managers have been asked to let staff attend in shifts. M: Smart. I'll handle the room reservations and ask the cafeteria to set up a healthy snack table. W: Thanks. Once everything is confirmed, I'll design a flyer and post it in the elevators and on the intranet.",
    "options": [
      "Reserve the meeting rooms",
      "Hire additional trainers",
      "Create and post a flyer",
      "Order healthy snacks"
    ],
    "answer": 2,
    "explanation": "여자는 마지막 대사에서 'Once everything is confirmed, I'll design a flyer and post it in the elevators and on the intranet.'이라고 말합니다. 전단을 디자인해 엘리베이터와 인트라넷에 게시하겠다는 것이므로 정답은 (C)입니다. (A) 회의실 예약과 (D) 간식 준비 요청은 남자가 맡은 일입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0064",
    "part": 3,
    "type": "LC",
    "question": "Where is the conversation most likely taking place?",
    "script": "M: Welcome to Fairmont Pharmacy. Are you picking up a prescription? W: Yes, it should be under Angela Moss. My doctor sent it over electronically this morning. M: Let me check. Yes, here it is — but I see the prescription is for a thirty-day supply, and your insurance plan only covers a twenty-eight-day refill cycle. There's a small difference you'd need to pay out of pocket. W: How much would that be? M: Just four dollars and fifty cents this time. Or, if you'd like, I can contact your doctor's office to adjust the prescription so it matches your plan and you avoid the charge next month. W: Yes, please contact them — but I'll pay the difference today since I'm leaving on a trip tomorrow and need the medication now. M: Understood. Give me about ten minutes to fill it, and I'll call your name when it's ready.",
    "options": [
      "At a doctor's office",
      "At a travel clinic",
      "At an insurance agency",
      "At a pharmacy"
    ],
    "answer": 3,
    "explanation": "남자는 첫 대사에서 'Welcome to Fairmont Pharmacy. Are you picking up a prescription?'이라고 말합니다. 처방약을 수령하러 온 손님과 약사의 대화이므로 정답은 (D)입니다. 의사 진료실이나 보험사가 아니라 약국에서 이루어지는 대화입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0065",
    "part": 3,
    "type": "LC",
    "question": "Why does the woman have to pay an extra charge?",
    "script": "M: Welcome to Fairmont Pharmacy. Are you picking up a prescription? W: Yes, it should be under Angela Moss. My doctor sent it over electronically this morning. M: Let me check. Yes, here it is — but I see the prescription is for a thirty-day supply, and your insurance plan only covers a twenty-eight-day refill cycle. There's a small difference you'd need to pay out of pocket. W: How much would that be? M: Just four dollars and fifty cents this time. Or, if you'd like, I can contact your doctor's office to adjust the prescription so it matches your plan and you avoid the charge next month. W: Yes, please contact them — but I'll pay the difference today since I'm leaving on a trip tomorrow and need the medication now. M: Understood. Give me about ten minutes to fill it, and I'll call your name when it's ready.",
    "options": [
      "Her insurance policy has expired",
      "The prescription exceeds her plan's refill cycle",
      "She requested express processing",
      "The medication is not covered at all"
    ],
    "answer": 1,
    "explanation": "남자는 'the prescription is for a thirty-day supply, and your insurance plan only covers a twenty-eight-day refill cycle. There's a small difference you'd need to pay out of pocket.'이라고 설명합니다. 처방은 30일분인데 보험은 28일 주기까지만 보장하므로 차액을 본인이 부담해야 한다는 것입니다. 정답은 (B)입니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0066",
    "part": 3,
    "type": "LC",
    "question": "Why does the woman decide to pay the difference today?",
    "script": "M: Welcome to Fairmont Pharmacy. Are you picking up a prescription? W: Yes, it should be under Angela Moss. My doctor sent it over electronically this morning. M: Let me check. Yes, here it is — but I see the prescription is for a thirty-day supply, and your insurance plan only covers a twenty-eight-day refill cycle. There's a small difference you'd need to pay out of pocket. W: How much would that be? M: Just four dollars and fifty cents this time. Or, if you'd like, I can contact your doctor's office to adjust the prescription so it matches your plan and you avoid the charge next month. W: Yes, please contact them — but I'll pay the difference today since I'm leaving on a trip tomorrow and need the medication now. M: Understood. Give me about ten minutes to fill it, and I'll call your name when it's ready.",
    "options": [
      "She is traveling soon and needs the medication",
      "She wants to earn loyalty points",
      "Her doctor's office is closed today",
      "The adjustment process costs more"
    ],
    "answer": 0,
    "explanation": "여자는 'I'll pay the difference today since I'm leaving on a trip tomorrow and need the medication now.'라고 말합니다. 내일 여행을 떠나기 때문에 지금 당장 약이 필요해서 오늘 차액을 지불하겠다는 것이므로 정답은 (A)입니다. 포인트 적립이나 병원 휴무, 비용 비교는 언급되지 않았습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0067",
    "part": 3,
    "type": "LC",
    "question": "What is the woman's problem?",
    "script": "W: Excuse me, I checked in online for the seven thirty flight to Denver, but the kiosk won't print my boarding pass. It keeps showing an error message. M: Let me take a look at your confirmation. Ah, I see what happened — the airline changed your flight to an eight forty-five departure due to crew scheduling, so your original boarding pass was voided. W: Eight forty-five? I have a connecting flight in Denver at eleven. Will I still make it? M: Your connection departs from the same terminal, and you'd land at ten ten, so you should have about fifty minutes. It's tight but doable. W: I'd rather not risk it. Are there any earlier options? M: There's a seat on the seven fifty flight with one stop in Salt Lake City, arriving in Denver at ten twenty-five. That's actually later than the direct one. W: Then I'll keep the eight forty-five and hope for the best. Could you print the new boarding pass for me? M: Of course. Here you are, and I've added a note so the gate staff in Denver know you have a tight connection.",
    "options": [
      "Her luggage has gone missing",
      "She arrived too late to check in",
      "Her passport has expired",
      "She cannot print her boarding pass"
    ],
    "answer": 3,
    "explanation": "여자는 첫 대사에서 'the kiosk won't print my boarding pass. It keeps showing an error message.'라고 말합니다. 키오스크에서 탑승권이 출력되지 않는 것이 여자의 문제이므로 정답은 (D)입니다. 수하물 분실, 여권 만료, 늦은 체크인은 언급되지 않았습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p3-0068",
    "part": 3,
    "type": "LC",
    "question": "Why was the woman's original boarding pass voided?",
    "script": "W: Excuse me, I checked in online for the seven thirty flight to Denver, but the kiosk won't print my boarding pass. It keeps showing an error message. M: Let me take a look at your confirmation. Ah, I see what happened — the airline changed your flight to an eight forty-five departure due to crew scheduling, so your original boarding pass was voided. W: Eight forty-five? I have a connecting flight in Denver at eleven. Will I still make it? M: Your connection departs from the same terminal, and you'd land at ten ten, so you should have about fifty minutes. It's tight but doable. W: I'd rather not risk it. Are there any earlier options? M: There's a seat on the seven fifty flight with one stop in Salt Lake City, arriving in Denver at ten twenty-five. That's actually later than the direct one. W: Then I'll keep the eight forty-five and hope for the best. Could you print the new boarding pass for me? M: Of course. Here you are, and I've added a note so the gate staff in Denver know you have a tight connection.",
    "options": [
      "Her ticket was purchased with expired miles",
      "The flight time was changed by the airline",
      "She entered the wrong confirmation number",
      "The aircraft was switched to a smaller model"
    ],
    "answer": 1,
    "explanation": "남자는 'the airline changed your flight to an eight forty-five departure due to crew scheduling, so your original boarding pass was voided'라고 설명합니다. 항공사가 승무원 일정 문제로 출발 시간을 변경하면서 기존 탑승권이 무효화된 것이므로 정답은 (B)입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0069",
    "part": 3,
    "type": "LC",
    "question": "What does the woman decide to do?",
    "script": "W: Excuse me, I checked in online for the seven thirty flight to Denver, but the kiosk won't print my boarding pass. It keeps showing an error message. M: Let me take a look at your confirmation. Ah, I see what happened — the airline changed your flight to an eight forty-five departure due to crew scheduling, so your original boarding pass was voided. W: Eight forty-five? I have a connecting flight in Denver at eleven. Will I still make it? M: Your connection departs from the same terminal, and you'd land at ten ten, so you should have about fifty minutes. It's tight but doable. W: I'd rather not risk it. Are there any earlier options? M: There's a seat on the seven fifty flight with one stop in Salt Lake City, arriving in Denver at ten twenty-five. That's actually later than the direct one. W: Then I'll keep the eight forty-five and hope for the best. Could you print the new boarding pass for me? M: Of course. Here you are, and I've added a note so the gate staff in Denver know you have a tight connection.",
    "options": [
      "Take the flight through Salt Lake City",
      "Book a different connecting flight",
      "Cancel her trip to Denver",
      "Stay on the rescheduled direct flight"
    ],
    "answer": 3,
    "explanation": "경유 항공편이 직항보다 오히려 늦게 도착한다는 설명을 듣고 여자는 'Then I'll keep the eight forty-five and hope for the best.'라고 말합니다. 변경된 8시 45분 직항편을 그대로 타기로 결정한 것이므로 정답은 (D)입니다. 솔트레이크시티 경유편은 선택하지 않았습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p3-0070",
    "part": 3,
    "type": "LC",
    "question": "What is the woman calling about?",
    "script": "W: Hello, this is Beatriz Lima from Crestline Manufacturing. I'm calling about the industrial printer we leased from your company. The print heads are misaligned again, and it's our third service call this quarter. M: I'm sorry to hear that, Ms. Lima. I see the previous two visits in our records. Since this is a recurring issue, you may be eligible for an equipment replacement under your lease agreement. W: A replacement would be ideal. The misalignment ruins about a tenth of our packaging labels, and we're falling behind on orders. M: I understand. Here's what I can do — I'll send a technician tomorrow morning for a temporary fix, and at the same time, I'll file a replacement request with our leasing department. W: How long does a replacement usually take to process? M: Typically five to seven business days. The new unit would be installed at no cost, and we'd extend your lease term by a month as compensation for the trouble. W: That sounds fair. Please send me the details in writing, and I'll have our operations manager review them.",
    "options": [
      "A renewal of a service contract",
      "An overdue invoice payment",
      "A delayed delivery of labels",
      "A malfunctioning leased printer"
    ],
    "answer": 3,
    "explanation": "여자는 첫 대사에서 'I'm calling about the industrial printer we leased from your company. The print heads are misaligned again'이라고 말합니다. 임대한 산업용 프린터의 헤드 정렬 불량이 또 발생해 전화한 것이므로 정답은 (D)입니다. 청구서, 라벨 배송 지연, 계약 갱신은 통화의 목적이 아닙니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0071",
    "part": 3,
    "type": "LC",
    "question": "Why might the woman be eligible for a replacement?",
    "script": "W: Hello, this is Beatriz Lima from Crestline Manufacturing. I'm calling about the industrial printer we leased from your company. The print heads are misaligned again, and it's our third service call this quarter. M: I'm sorry to hear that, Ms. Lima. I see the previous two visits in our records. Since this is a recurring issue, you may be eligible for an equipment replacement under your lease agreement. W: A replacement would be ideal. The misalignment ruins about a tenth of our packaging labels, and we're falling behind on orders. M: I understand. Here's what I can do — I'll send a technician tomorrow morning for a temporary fix, and at the same time, I'll file a replacement request with our leasing department. W: How long does a replacement usually take to process? M: Typically five to seven business days. The new unit would be installed at no cost, and we'd extend your lease term by a month as compensation for the trouble. W: That sounds fair. Please send me the details in writing, and I'll have our operations manager review them.",
    "options": [
      "She purchased an extended warranty",
      "The problem has occurred repeatedly",
      "The printer model has been recalled",
      "Her company is a long-term customer"
    ],
    "answer": 1,
    "explanation": "남자는 'Since this is a recurring issue, you may be eligible for an equipment replacement under your lease agreement.'라고 말합니다. 같은 문제가 반복적으로 발생했기 때문에(이번 분기 세 번째 서비스 요청) 임대 계약에 따라 교체 대상이 될 수 있다는 것이므로 정답은 (B)입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p3-0072",
    "part": 3,
    "type": "LC",
    "question": "What will the man do tomorrow morning?",
    "script": "W: Hello, this is Beatriz Lima from Crestline Manufacturing. I'm calling about the industrial printer we leased from your company. The print heads are misaligned again, and it's our third service call this quarter. M: I'm sorry to hear that, Ms. Lima. I see the previous two visits in our records. Since this is a recurring issue, you may be eligible for an equipment replacement under your lease agreement. W: A replacement would be ideal. The misalignment ruins about a tenth of our packaging labels, and we're falling behind on orders. M: I understand. Here's what I can do — I'll send a technician tomorrow morning for a temporary fix, and at the same time, I'll file a replacement request with our leasing department. W: How long does a replacement usually take to process? M: Typically five to seven business days. The new unit would be installed at no cost, and we'd extend your lease term by a month as compensation for the trouble. W: That sounds fair. Please send me the details in writing, and I'll have our operations manager review them.",
    "options": [
      "Deliver a brand-new printer",
      "Cancel the lease agreement",
      "Visit the manufacturing plant himself",
      "Send a technician for a temporary repair"
    ],
    "answer": 3,
    "explanation": "남자는 'I'll send a technician tomorrow morning for a temporary fix'라고 말합니다. 내일 아침 기술자를 보내 임시 수리를 하게 하고, 동시에 교체 요청서를 접수하겠다는 것이므로 정답은 (D)입니다. 새 프린터 설치는 교체 승인 후 5~7영업일이 걸리는 별도의 절차입니다.",
    "difficulty": "easy"
  }
];
