// Auto-generated by question_pipeline/build_bank.cjs — 직접 수정하지 마세요.
// 데이터 출처: question_pipeline/reviewed/ (에이전트 파이프라인 검수 완료분)
import { BankQuestion } from './index';

export const PART4_QUESTIONS: BankQuestion[] = [];
