// Auto-generated by question_pipeline/build_bank.cjs — 직접 수정하지 마세요.
// 데이터 출처: question_pipeline/reviewed/ (에이전트 파이프라인 검수 완료분)
import { BankQuestion } from './index';

export const PART6_QUESTIONS: BankQuestion[] = [
  {
    "id": "p6-0001",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: All Employees\nFrom: Dana Whitfield, Operations Manager\nSubject: Office Relocation\n\nPlease be advised that our headquarters will move to the Riverside Tower _______ July 15. The new building offers larger meeting rooms and convenient access to public transportation. It is located just two blocks from the Central Subway Station. Packing boxes will be distributed to each department next Monday. All staff are asked to label their belongings clearly before the move. The IT team will disconnect computers on July 11; therefore, please save all important files to the shared drive beforehand.",
    "options": [
      "in",
      "at",
      "until",
      "on"
    ],
    "answer": 3,
    "explanation": "빈칸 뒤에 'July 15'라는 특정 날짜가 나오므로 날짜 앞에 쓰는 전치사 'on'이 정답입니다. 'in'은 월·연도 앞(in July), 'at'은 시각 앞(at 3 P.M.)에 쓰이며, 'until'은 '~까지 계속'이라는 지속의 의미라 단발성 사건인 이사 날짜와 어울리지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0002",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: All Employees\nFrom: Dana Whitfield, Operations Manager\nSubject: Office Relocation\n\nPlease be advised that our headquarters will move to the Riverside Tower on July 15. The new building offers larger meeting rooms and convenient access to public transportation. _______ Packing boxes will be distributed to each department next Monday. All staff are asked to label their belongings clearly before the move. The IT team will disconnect computers on July 11; therefore, please save all important files to the shared drive beforehand.",
    "options": [
      "It is located just two blocks from the Central Subway Station.",
      "The cafeteria menu will change every week.",
      "Employees must renew their parking permits annually.",
      "The old building was constructed in 1982."
    ],
    "answer": 0,
    "explanation": "빈칸 앞 문장에서 새 건물이 '대중교통 접근성이 좋다(convenient access to public transportation)'고 언급했으므로, 지하철역에서 두 블록 거리라는 구체적인 위치 정보를 덧붙이는 문장이 흐름상 가장 자연스럽습니다. 구내식당 메뉴, 주차권 갱신, 옛 건물의 건축 연도는 앞뒤 문맥과 연결되지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0003",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: All Employees\nFrom: Dana Whitfield, Operations Manager\nSubject: Office Relocation\n\nPlease be advised that our headquarters will move to the Riverside Tower on July 15. The new building offers larger meeting rooms and convenient access to public transportation. It is located just two blocks from the Central Subway Station. Packing boxes will be distributed to each department next Monday. All staff are asked to label their _______ clearly before the move. The IT team will disconnect computers on July 11; therefore, please save all important files to the shared drive beforehand.",
    "options": [
      "decisions",
      "belongings",
      "qualifications",
      "permissions"
    ],
    "answer": 1,
    "explanation": "이사 전에 직원들이 '라벨을 붙여야 하는' 대상이므로 '소지품, 개인 물품'을 뜻하는 'belongings'가 정답입니다. decisions(결정), qualifications(자격), permissions(허가)는 상자에 라벨을 붙이는 이사 상황과 의미가 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0004",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: All Employees\nFrom: Dana Whitfield, Operations Manager\nSubject: Office Relocation\n\nPlease be advised that our headquarters will move to the Riverside Tower on July 15. The new building offers larger meeting rooms and convenient access to public transportation. It is located just two blocks from the Central Subway Station. Packing boxes will be distributed to each department next Monday. All staff are asked to label their belongings clearly before the move. The IT team will disconnect computers on July 11; _______, please save all important files to the shared drive beforehand.",
    "options": [
      "however",
      "therefore",
      "otherwise",
      "similarly"
    ],
    "answer": 1,
    "explanation": "앞 절에서 'IT팀이 7월 11일에 컴퓨터를 분리한다'고 했고, 뒤 절은 '미리 파일을 공유 드라이브에 저장하라'는 당부입니다. 앞 내용이 원인, 뒤 내용이 그에 따른 결과·조치이므로 인과 관계를 나타내는 접속부사 'therefore(그러므로)'가 정답입니다. however(그러나)는 역접, otherwise(그렇지 않으면)는 조건, similarly(마찬가지로)는 유사 관계라 어색합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0005",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "NOTICE TO ALL TENANTS\n\nThe underground parking garage will be closed for resurfacing from March 3 to March 7. During this period, tenants _______ to use the public lot on Harper Street at no charge. Please display the temporary permit on your dashboard so that attendants can easily identify your vehicle. Permits can be picked up at the management office starting this Friday. We apologize for any inconvenience this work may cause. However, the improvements will provide a smoother and safer surface for everyone.",
    "options": [
      "encourage",
      "are encouraged",
      "encouraging",
      "have encouraged"
    ],
    "answer": 1,
    "explanation": "주어 'tenants(입주민들)'는 무료 주차장 이용을 '권장받는' 대상이므로 수동태 'are encouraged (to use)'가 정답입니다. 'be encouraged to do(~하도록 권장되다)' 구문을 묻는 문제로, 능동형 encourage/have encouraged는 입주민이 누군가를 권장한다는 어색한 의미가 되고, encouraging은 본동사가 없어 문장이 성립하지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0006",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "NOTICE TO ALL TENANTS\n\nThe underground parking garage will be closed for resurfacing from March 3 to March 7. During this period, tenants are encouraged to use the public lot on Harper Street at no charge. Please display the temporary permit on your dashboard so that attendants can easily _______ your vehicle. Permits can be picked up at the management office starting this Friday. We apologize for any inconvenience this work may cause. However, the improvements will provide a smoother and safer surface for everyone.",
    "options": [
      "imitate",
      "persuade",
      "decline",
      "identify"
    ],
    "answer": 3,
    "explanation": "임시 주차권을 대시보드에 놓아 두면 관리인이 차량을 쉽게 '식별할' 수 있다는 문맥이므로 'identify(식별하다, 알아보다)'가 정답입니다. imitate(모방하다), persuade(설득하다), decline(거절하다)은 차량과 주차권의 관계에 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0007",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "NOTICE TO ALL TENANTS\n\nThe underground parking garage will be closed for resurfacing from March 3 to March 7. During this period, tenants are encouraged to use the public lot on Harper Street at no charge. Please display the temporary permit on your dashboard so that attendants can easily identify your vehicle. _______ We apologize for any inconvenience this work may cause. However, the improvements will provide a smoother and safer surface for everyone.",
    "options": [
      "Permits can be picked up at the management office starting this Friday.",
      "The garage was originally built for 200 vehicles.",
      "Monthly rent payments are due on the first of each month.",
      "Several tenants have recently purchased new cars."
    ],
    "answer": 0,
    "explanation": "바로 앞 문장에서 '임시 주차권(temporary permit)을 대시보드에 게시하라'고 안내했으므로, 그 주차권을 어디서 언제 받을 수 있는지 알려 주는 문장이 가장 자연스럽게 이어집니다. 차고의 원래 수용 대수, 월세 납부일, 입주민의 새 차 구입은 공사 안내라는 글의 목적과 무관합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0008",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "NOTICE TO ALL TENANTS\n\nThe underground parking garage will be closed for resurfacing from March 3 to March 7. During this period, tenants are encouraged to use the public lot on Harper Street at no charge. Please display the temporary permit on your dashboard so that attendants can easily identify your vehicle. Permits can be picked up at the management office starting this Friday. We apologize for any inconvenience this work may cause. _______, the improvements will provide a smoother and safer surface for everyone.",
    "options": [
      "Therefore",
      "For example",
      "However",
      "Similarly"
    ],
    "answer": 2,
    "explanation": "앞 문장은 '불편을 끼쳐 죄송하다'는 사과이고, 뒤 문장은 '공사가 끝나면 더 매끄럽고 안전한 노면이 제공된다'는 긍정적인 내용입니다. 부정적 내용에서 긍정적 내용으로 흐름이 전환되므로 역접의 접속부사 'However(그러나)'가 정답입니다. Therefore(그러므로)·For example(예를 들어)·Similarly(마찬가지로)는 대조 관계를 나타내지 못합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0009",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "GREENFIELD — Local bakery chain Maple & Crust announced on Tuesday that it will open three new locations across the county by the end of the year. The company, _______ first store opened in 2015, has grown rapidly thanks to its line of organic breads. Demand for its products has nearly doubled over the past two years. According to founder Elena Ruiz, the expansion will create about forty new jobs. Construction on the first new site is scheduled to begin early next month. Analysts expect the chain's revenue to rise by 20 percent next year.",
    "options": [
      "who",
      "which",
      "whose",
      "whom"
    ],
    "answer": 2,
    "explanation": "빈칸 뒤의 'first store(첫 매장)'는 선행사 'The company'의 소유 대상이므로 소유격 관계대명사 'whose'가 정답입니다. '그 회사의 첫 매장이 2015년에 문을 열었다'는 의미가 됩니다. who/whom은 사람 선행사에 쓰이고, which를 쓰면 뒤에 완전한 절을 이끌 주어 자리가 어긋나 비문이 됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0010",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "GREENFIELD — Local bakery chain Maple & Crust announced on Tuesday that it will open three new locations across the county by the end of the year. The company, whose first store opened in 2015, has grown rapidly thanks to its line of organic breads. _______ According to founder Elena Ruiz, the expansion will create about forty new jobs. Construction on the first new site is scheduled to begin early next month. Analysts expect the chain's revenue to rise by 20 percent next year.",
    "options": [
      "The recipe for its signature loaf remains a secret.",
      "Demand for its products has nearly doubled over the past two years.",
      "Bread prices nationwide have fallen this quarter.",
      "Ms. Ruiz previously worked as an accountant."
    ],
    "answer": 1,
    "explanation": "앞 문장에서 회사가 '유기농 빵 제품군 덕분에 빠르게 성장했다'고 했고, 뒤 문장에서는 확장과 신규 고용을 언급합니다. 성장의 근거로 '지난 2년간 수요가 거의 두 배로 늘었다'는 문장이 들어가야 확장 결정과 자연스럽게 연결됩니다. 비법 레시피, 전국 빵값 하락, 창업자의 전직은 성장과 확장이라는 기사 흐름을 뒷받침하지 못합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0011",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "GREENFIELD — Local bakery chain Maple & Crust announced on Tuesday that it will open three new locations across the county by the end of the year. The company, whose first store opened in 2015, has grown rapidly thanks to its line of organic breads. Demand for its products has nearly doubled over the past two years. According to founder Elena Ruiz, the expansion will create about forty new jobs. Construction on the first new site is scheduled to begin _______ next month. Analysts expect the chain's revenue to rise by 20 percent next year.",
    "options": [
      "early",
      "soon",
      "yet",
      "once"
    ],
    "answer": 0,
    "explanation": "'begin _______ next month'에서 'early next month(다음 달 초에)'라는 표현이 가장 자연스럽습니다. early가 next month를 수식하여 시기를 구체화합니다. soon은 'soon next month'로 겹쳐 쓸 수 없고, yet은 부정문·의문문에 주로 쓰이며, once는 '한 번' 또는 접속사 '일단 ~하면'이라 어울리지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0012",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "GREENFIELD — Local bakery chain Maple & Crust announced on Tuesday that it will open three new locations across the county by the end of the year. The company, whose first store opened in 2015, has grown rapidly thanks to its line of organic breads. Demand for its products has nearly doubled over the past two years. According to founder Elena Ruiz, the expansion will create about forty new jobs. Construction on the first new site is scheduled to begin early next month. Analysts expect the chain's revenue to _______ by 20 percent next year.",
    "options": [
      "raise",
      "arise",
      "rise",
      "lift"
    ],
    "answer": 2,
    "explanation": "'revenue(수익)가 20퍼센트 오르다'라는 자동사 표현이 필요하므로 'rise(오르다)'가 정답입니다. raise와 lift는 목적어가 필요한 타동사이고, arise는 '(문제 등이) 발생하다'라는 뜻이라 수치 상승을 나타내지 못합니다. rise(자동사)와 raise(타동사)의 구분은 토익 빈출 포인트입니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0013",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Join Summit Fitness today and discover a healthier you! Our newly renovated facility features modern equipment, an indoor pool, and over thirty group classes each week. Sign up before August 31 and receive a 20 percent discount on an annual _______. New members will also receive a complimentary fitness assessment. Our certified trainers will design a personal program that fits your schedule and goals. Whether you prefer morning yoga or evening cycling, there is a class for you. Visit www.summitfit.com or stop by our front desk for more information.",
    "options": [
      "membership",
      "appliance",
      "inventory",
      "expense"
    ],
    "answer": 0,
    "explanation": "피트니스 센터 광고에서 '연간 ____ 20% 할인'이라고 했으므로 '회원권'을 뜻하는 'membership'이 정답입니다. annual membership(연간 회원권)은 헬스장 광고의 전형적인 표현입니다. appliance(가전제품), inventory(재고), expense(지출)는 할인 대상으로 문맥에 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0014",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Join Summit Fitness today and discover a healthier you! Our newly renovated facility features modern equipment, an indoor pool, and over thirty group classes each week. Sign up before August 31 and receive a 20 percent discount on an annual membership. _______ Our certified trainers will design a personal program that fits your schedule and goals. Whether you prefer morning yoga or evening cycling, there is a class for you. Visit www.summitfit.com or stop by our front desk for more information.",
    "options": [
      "The pool will be closed for cleaning all summer.",
      "Our previous location had limited parking.",
      "New members will also receive a complimentary fitness assessment.",
      "Group classes require your own equipment."
    ],
    "answer": 2,
    "explanation": "앞 문장에서 가입 혜택(20% 할인)을 제시했고, 뒤 문장에서 트레이너가 개인 프로그램을 설계해 준다고 했습니다. 따라서 '신규 회원에게 무료 체력 측정도 제공된다'는 추가 혜택 문장이 들어가야 할인 혜택과 개인 프로그램 안내 사이를 자연스럽게 연결합니다. 수영장 폐쇄나 장비 지참 요구는 광고의 긍정적 어조와 모순됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0015",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Join Summit Fitness today and discover a healthier you! Our newly renovated facility features modern equipment, an indoor pool, and over thirty group classes each week. Sign up before August 31 and receive a 20 percent discount on an annual membership. New members will also receive a complimentary fitness assessment. Our certified trainers will design a personal program that fits your schedule and goals. _______ you prefer morning yoga or evening cycling, there is a class for you. Visit www.summitfit.com or stop by our front desk for more information.",
    "options": [
      "Either",
      "Whether",
      "Despite",
      "Unless"
    ],
    "answer": 1,
    "explanation": "'_______ you prefer A or B'는 '당신이 A를 좋아하든 B를 좋아하든'이라는 양보의 부사절이므로 'Whether ~ or' 구문이 정답입니다. Either는 'either A or B' 형태로 절을 이끌 수 없고, Despite는 전치사라 뒤에 절이 올 수 없으며, Unless(~하지 않는 한)는 의미가 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0016",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Join Summit Fitness today and discover a healthier you! Our newly renovated facility features modern equipment, an indoor pool, and over thirty group classes each week. Sign up before August 31 and receive a 20 percent discount on an annual membership. New members will also receive a complimentary fitness assessment. Our certified trainers will design a personal program that fits your schedule and goals. Whether you prefer morning yoga or evening cycling, there is a class for you. Visit www.summitfit.com or stop by our front desk for more _______.",
    "options": [
      "inform",
      "informative",
      "information",
      "informed"
    ],
    "answer": 2,
    "explanation": "전치사구 'for more _______'에서 형용사 more의 수식을 받는 명사 자리이므로 'information(정보)'이 정답입니다. inform은 동사, informative는 형용사, informed는 과거분사로 명사 자리에 올 수 없습니다. 'for more information(자세한 내용은)'은 안내문·광고의 상투적 표현입니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0017",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Calloway,\n\nThank you for contacting us about the damaged coffee table you received on April 2. We sincerely apologize for the _______ this has caused. After reviewing the photographs you sent, we have confirmed that the item was damaged during shipping. You do not need to return the damaged item. A replacement table will be delivered to your home within five business days. In addition, we have included a voucher for 15 percent off your next purchase. If you have any further questions, please do not hesitate to contact our customer service team.\n\nSincerely,\nRita Moreau",
    "options": [
      "inconvenience",
      "achievement",
      "appearance",
      "celebration"
    ],
    "answer": 0,
    "explanation": "파손된 상품에 대해 사과하는 문맥이므로 '불편'을 뜻하는 'inconvenience'가 정답입니다. 'apologize for the inconvenience(불편을 끼쳐 죄송합니다)'는 고객 응대 서신의 대표적인 표현입니다. achievement(성취), appearance(외관), celebration(축하)은 사과의 대상이 될 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0018",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Calloway,\n\nThank you for contacting us about the damaged coffee table you received on April 2. We sincerely apologize for the inconvenience this has caused. After reviewing the photographs you sent, we have confirmed that the item was damaged during shipping. _______ A replacement table will be delivered to your home within five business days. In addition, we have included a voucher for 15 percent off your next purchase. If you have any further questions, please do not hesitate to contact our customer service team.\n\nSincerely,\nRita Moreau",
    "options": [
      "Our store will be closed for renovations next month.",
      "You do not need to return the damaged item.",
      "The table is available in three different colors.",
      "We no longer accept payment by check."
    ],
    "answer": 1,
    "explanation": "앞에서 '배송 중 파손이 확인되었다'고 했고, 뒤에서 '교체 상품이 5영업일 내에 배송된다'고 안내합니다. 그 사이에는 파손된 기존 상품의 처리 방법, 즉 '파손품을 반품할 필요가 없다'는 문장이 들어가는 것이 가장 논리적입니다. 매장 보수 공사, 색상 종류, 결제 수단 변경은 교환 절차 안내와 무관합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0019",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Calloway,\n\nThank you for contacting us about the damaged coffee table you received on April 2. We sincerely apologize for the inconvenience this has caused. After reviewing the photographs you sent, we have confirmed that the item was damaged during shipping. You do not need to return the damaged item. A replacement table will be delivered to your home within five business days. _______, we have included a voucher for 15 percent off your next purchase. If you have any further questions, please do not hesitate to contact our customer service team.\n\nSincerely,\nRita Moreau",
    "options": [
      "However",
      "In addition",
      "Otherwise",
      "Nevertheless"
    ],
    "answer": 1,
    "explanation": "앞 문장에서 '교체 상품 배송'이라는 보상 조치를 제시했고, 빈칸 뒤에서 '다음 구매 시 15% 할인 쿠폰'이라는 또 다른 혜택을 추가하고 있습니다. 혜택이 첨가되는 흐름이므로 'In addition(게다가)'이 정답입니다. However/Nevertheless(그러나)는 역접, Otherwise(그렇지 않으면)는 조건의 의미라 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0020",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Calloway,\n\nThank you for contacting us about the damaged coffee table you received on April 2. We sincerely apologize for the inconvenience this has caused. After reviewing the photographs you sent, we have confirmed that the item was damaged during shipping. You do not need to return the damaged item. A replacement table will be delivered to your home within five business days. In addition, we have included a voucher for 15 percent off your next purchase. If you have any further questions, please do not hesitate to _______ our customer service team.\n\nSincerely,\nRita Moreau",
    "options": [
      "respond",
      "inquire",
      "reply",
      "contact"
    ],
    "answer": 3,
    "explanation": "빈칸 뒤에 목적어 'our customer service team'이 바로 오므로 타동사 'contact(~에게 연락하다)'가 정답입니다. respond·reply는 'respond/reply to + 대상'처럼 전치사 to가 필요하고, inquire도 'inquire about/of' 형태로 쓰여 목적어를 바로 취할 수 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0021",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: Marketing Team\nFrom: Joel Park\nSubject: Quarterly Review Meeting\n\nHi everyone,\n\nThe quarterly review meeting originally scheduled for Thursday has been _______ to Friday at 10 A.M. because several team members will be attending the trade fair. The meeting will be held in Conference Room B instead of the usual third-floor room, which is being repainted. A video link will be available for those who cannot attend in person. Please review the attached sales report before you arrive so that we can use our time efficiently.\n\nThanks,\nJoel",
    "options": [
      "expired",
      "postponed",
      "dismissed",
      "retrieved"
    ],
    "answer": 1,
    "explanation": "목요일로 예정되어 있던 회의가 금요일'로(to Friday)' 옮겨졌다는 문맥이므로 'postponed(연기되다)'가 정답입니다. 'be postponed to + 날짜'는 일정 변경을 알리는 빈출 표현입니다. expired(만료되다), dismissed(해산되다·해고되다), retrieved(회수되다)는 회의 일정 변경과 어울리지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0022",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: Marketing Team\nFrom: Joel Park\nSubject: Quarterly Review Meeting\n\nHi everyone,\n\nThe quarterly review meeting originally scheduled for Thursday has been postponed to Friday at 10 A.M. because several team members will be attending the trade fair. The meeting will be held in Conference Room B _______ of the usual third-floor room, which is being repainted. A video link will be available for those who cannot attend in person. Please review the attached sales report before you arrive so that we can use our time efficiently.\n\nThanks,\nJoel",
    "options": [
      "despite",
      "except",
      "instead",
      "rather"
    ],
    "answer": 2,
    "explanation": "'평소의 3층 회의실 대신 B 회의실에서 열린다'는 의미이므로 'instead of(~ 대신에)'를 만드는 'instead'가 정답입니다. 빈칸 뒤의 of와 결합하는 형태에 주목해야 합니다. despite는 'despite + 명사'로 단독으로 쓰이고, except of나 rather of는 성립하지 않는 형태입니다(rather는 rather than).",
    "difficulty": "medium"
  },
  {
    "id": "p6-0023",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: Marketing Team\nFrom: Joel Park\nSubject: Quarterly Review Meeting\n\nHi everyone,\n\nThe quarterly review meeting originally scheduled for Thursday has been postponed to Friday at 10 A.M. because several team members will be attending the trade fair. The meeting will be held in Conference Room B instead of the usual third-floor room, which is being repainted. _______ Please review the attached sales report before you arrive so that we can use our time efficiently.\n\nThanks,\nJoel",
    "options": [
      "The trade fair was canceled at the last minute.",
      "A video link will be available for those who cannot attend in person.",
      "The sales report will be written next quarter.",
      "Conference Room B seats only four people."
    ],
    "answer": 1,
    "explanation": "일정과 장소 변경을 안내한 뒤, 참석 준비를 당부하기 전에 들어갈 문장으로는 '직접 참석하지 못하는 사람을 위해 화상 링크가 제공된다'는 보완 안내가 가장 적절합니다. 무역 박람회 취소는 첫 문장의 연기 사유와 모순되고, 보고서를 다음 분기에 작성한다는 내용은 '첨부된 보고서를 검토하라'는 뒤 문장과 충돌하며, 4인용 회의실은 팀 회의 장소 안내로 부자연스럽습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0024",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "To: Marketing Team\nFrom: Joel Park\nSubject: Quarterly Review Meeting\n\nHi everyone,\n\nThe quarterly review meeting originally scheduled for Thursday has been postponed to Friday at 10 A.M. because several team members will be attending the trade fair. The meeting will be held in Conference Room B instead of the usual third-floor room, which is being repainted. A video link will be available for those who cannot attend in person. Please review the attached sales report before you arrive so that we can use our time _______.\n\nThanks,\nJoel",
    "options": [
      "efficient",
      "efficiency",
      "efficiently",
      "efficiencies"
    ],
    "answer": 2,
    "explanation": "동사구 'use our time'을 수식하는 자리이므로 부사 'efficiently(효율적으로)'가 정답입니다. '시간을 효율적으로 쓰다'라는 의미로, 동사를 수식할 수 있는 품사는 부사뿐입니다. efficient는 형용사, efficiency/efficiencies는 명사라 동사를 수식할 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0025",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Department Heads\nFrom: Finance Office\nRe: Updated Expense Policy\n\nEffective May 1, all travel expenses must be submitted through the new online portal. Paper forms will no longer be _______. Receipts should be uploaded within ten days of the completion of each trip. Step-by-step instructions are posted on the company intranet. Employees who fail to meet the deadline may experience delays in reimbursement. Furthermore, approval from a direct supervisor is now required for any expense over $500. Questions may be directed to extension 4521.",
    "options": [
      "accepted",
      "accepting",
      "acceptance",
      "accepts"
    ],
    "answer": 0,
    "explanation": "주어 'Paper forms(종이 양식)'는 '받아들여지는' 대상이므로 수동태를 완성하는 과거분사 'accepted'가 정답입니다. 'will no longer be accepted(더 이상 접수되지 않는다)'의 형태입니다. accepting은 능동 진행, accepts는 단수 동사, acceptance는 명사라 be동사 뒤 수동태 자리에 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0026",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Department Heads\nFrom: Finance Office\nRe: Updated Expense Policy\n\nEffective May 1, all travel expenses must be submitted through the new online portal. Paper forms will no longer be accepted. Receipts should be uploaded within ten days of the _______ of each trip. Step-by-step instructions are posted on the company intranet. Employees who fail to meet the deadline may experience delays in reimbursement. Furthermore, approval from a direct supervisor is now required for any expense over $500. Questions may be directed to extension 4521.",
    "options": [
      "admission",
      "completion",
      "foundation",
      "collision"
    ],
    "answer": 1,
    "explanation": "'각 출장의 _______ 후 10일 이내에 영수증을 업로드하라'는 문맥이므로 '완료, 종료'를 뜻하는 'completion'이 정답입니다. 'within ten days of the completion of each trip(각 출장이 끝난 뒤 10일 이내)'이 자연스럽습니다. admission(입장·입학), foundation(설립), collision(충돌)은 출장과 어울리지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0027",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Department Heads\nFrom: Finance Office\nRe: Updated Expense Policy\n\nEffective May 1, all travel expenses must be submitted through the new online portal. Paper forms will no longer be accepted. Receipts should be uploaded within ten days of the completion of each trip. _______ Employees who fail to meet the deadline may experience delays in reimbursement. Furthermore, approval from a direct supervisor is now required for any expense over $500. Questions may be directed to extension 4521.",
    "options": [
      "Step-by-step instructions are posted on the company intranet.",
      "The finance office will be closed for the holiday.",
      "Travel to overseas branches has been suspended.",
      "Last year's budget exceeded expectations."
    ],
    "answer": 0,
    "explanation": "새 온라인 포털 사용과 영수증 업로드 절차를 설명한 직후이므로, 그 절차를 어떻게 따라 하는지 알려 주는 '단계별 안내가 사내 인트라넷에 게시되어 있다'는 문장이 가장 적절합니다. 재무팀 휴무, 해외 출장 중단, 작년 예산 이야기는 새 경비 처리 절차 안내라는 메모의 목적에서 벗어납니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0028",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Department Heads\nFrom: Finance Office\nRe: Updated Expense Policy\n\nEffective May 1, all travel expenses must be submitted through the new online portal. Paper forms will no longer be accepted. Receipts should be uploaded within ten days of the completion of each trip. Step-by-step instructions are posted on the company intranet. Employees who fail to meet the deadline may experience delays in reimbursement. _______, approval from a direct supervisor is now required for any expense over $500. Questions may be directed to extension 4521.",
    "options": [
      "Otherwise",
      "Nonetheless",
      "For instance",
      "Furthermore"
    ],
    "answer": 3,
    "explanation": "앞에서 '기한을 어기면 환급이 지연될 수 있다'는 규정을 말했고, 빈칸 뒤에서 '500달러 초과 경비는 직속 상사의 승인이 필요하다'는 또 다른 새 규정을 덧붙이고 있습니다. 규정이 추가되는 흐름이므로 첨가의 접속부사 'Furthermore(더욱이, 게다가)'가 정답입니다. Otherwise(그렇지 않으면), Nonetheless(그럼에도), For instance(예를 들어)는 첨가 관계를 나타내지 못합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0029",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Grand Opening — Harbor Lane Bistro!\n\nJoin us on Saturday, June 21, as we celebrate the opening of our waterfront restaurant. Enjoy fresh seafood dishes _______ by award-winning chef Marco Bellini. The first fifty guests will receive a free appetizer, and live jazz will be performed throughout the evening. Outdoor terrace tables offer a beautiful view of the marina. Reservations are strongly recommended, as seating is limited. To book a table, call 555-0182 or visit our website. We look forward to serving you at Harbor Lane Bistro!",
    "options": [
      "preparing",
      "prepared",
      "prepares",
      "preparation"
    ],
    "answer": 1,
    "explanation": "'요리(dishes)'는 셰프에 의해 '준비되는' 대상이므로 수동의 의미를 갖는 과거분사 'prepared'가 정답입니다. 'dishes (which are) prepared by chef ~'에서 '주격 관계대명사 + be동사'가 생략된 구조입니다. preparing은 능동(요리가 스스로 준비한다는 의미)이 되어 어색하고, prepares는 동사, preparation은 명사라 명사를 뒤에서 수식할 수 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0030",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Grand Opening — Harbor Lane Bistro!\n\nJoin us on Saturday, June 21, as we celebrate the opening of our waterfront restaurant. Enjoy fresh seafood dishes prepared by award-winning chef Marco Bellini. The first fifty guests will receive a free appetizer, and live jazz will be performed _______ the evening. Outdoor terrace tables offer a beautiful view of the marina. Reservations are strongly recommended, as seating is limited. To book a table, call 555-0182 or visit our website. We look forward to serving you at Harbor Lane Bistro!",
    "options": [
      "among",
      "onto",
      "throughout",
      "beside"
    ],
    "answer": 2,
    "explanation": "'저녁 내내 라이브 재즈가 연주된다'는 의미가 자연스러우므로 기간 전체에 걸침을 나타내는 'throughout(~ 내내)'이 정답입니다. 'throughout the evening'은 시간 표현과 함께 쓰이는 대표적 형태입니다. among(~ 사이에), onto(~ 위로), beside(~ 옆에)는 장소·방향의 전치사라 시간 표현과 어울리지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0031",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Grand Opening — Harbor Lane Bistro!\n\nJoin us on Saturday, June 21, as we celebrate the opening of our waterfront restaurant. Enjoy fresh seafood dishes prepared by award-winning chef Marco Bellini. The first fifty guests will receive a free appetizer, and live jazz will be performed throughout the evening. _______ Reservations are strongly recommended, as seating is limited. To book a table, call 555-0182 or visit our website. We look forward to serving you at Harbor Lane Bistro!",
    "options": [
      "The restaurant will be closed on Sundays in July.",
      "Chef Bellini retired from cooking last year.",
      "Outdoor terrace tables offer a beautiful view of the marina.",
      "Parking fines have recently increased downtown."
    ],
    "answer": 2,
    "explanation": "수변(waterfront) 레스토랑의 개업을 홍보하면서 좌석 예약을 권하기 직전이므로, '야외 테라스 좌석에서 마리나 전망을 즐길 수 있다'는 매력 포인트를 덧붙이는 문장이 가장 자연스럽습니다. 일요일 휴무나 주차 벌금 인상은 홍보 효과를 떨어뜨리고, 셰프가 작년에 은퇴했다는 내용은 그가 요리를 담당한다는 앞 문장과 모순됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0032",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Grand Opening — Harbor Lane Bistro!\n\nJoin us on Saturday, June 21, as we celebrate the opening of our waterfront restaurant. Enjoy fresh seafood dishes prepared by award-winning chef Marco Bellini. The first fifty guests will receive a free appetizer, and live jazz will be performed throughout the evening. Outdoor terrace tables offer a beautiful view of the marina. Reservations are strongly recommended, as seating is limited. To book a table, call 555-0182 or visit our website. We look forward to _______ you at Harbor Lane Bistro!",
    "options": [
      "serve",
      "served",
      "serving",
      "serves"
    ],
    "answer": 2,
    "explanation": "'look forward to'의 to는 전치사이므로 뒤에는 동명사가 와야 합니다. 따라서 'serving'이 정답입니다. 'We look forward to serving you(여러분을 모시기를 기대합니다)'는 서비스 업계의 상투 표현입니다. to를 부정사로 착각하여 동사원형 serve를 고르지 않도록 주의해야 하는 토익 단골 함정입니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0033",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PORTVILLE — The number of visitors to Portville rose sharply last summer, according to a report released by the city's tourism board. Nearly 600,000 tourists visited the coastal town between June and August, a 25 percent _______ over the previous year. Officials credit the new ferry service connecting Portville with the regional airport. Local restaurants and shops have also reported record sales. Hotel owners, however, say more accommodations are urgently needed. The city council will vote next month on a proposal to approve the construction of two new hotels.",
    "options": [
      "increase",
      "decrease",
      "balance",
      "estimate"
    ],
    "answer": 0,
    "explanation": "방문객 수가 '급격히 늘었다(rose sharply)'고 했으므로 전년 대비 '25퍼센트 증가'를 뜻하는 'increase'가 정답입니다. 'a 25 percent increase over the previous year'는 수치 변화를 나타내는 전형적인 표현입니다. decrease(감소)는 앞 내용과 모순되고, balance(균형)와 estimate(추정치)는 증가 폭을 나타내지 못합니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0034",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PORTVILLE — The number of visitors to Portville rose sharply last summer, according to a report released by the city's tourism board. Nearly 600,000 tourists visited the coastal town between June and August, a 25 percent increase over the previous year. Officials credit the new ferry service connecting Portville with the regional airport. _______ Hotel owners, however, say more accommodations are urgently needed. The city council will vote next month on a proposal to approve the construction of two new hotels.",
    "options": [
      "Ferry tickets must be purchased two weeks in advance.",
      "Local restaurants and shops have also reported record sales.",
      "The airport will close one of its runways this fall.",
      "Portville's population has declined for a decade."
    ],
    "answer": 1,
    "explanation": "앞에서 관광객 급증과 그 요인(새 페리 노선)을 설명했으므로, 관광 호황의 또 다른 결과로 '지역 식당과 상점도 기록적인 매출을 보고했다'는 문장이 이어지는 것이 가장 자연스럽습니다. also가 앞 내용과의 연결 고리 역할을 합니다. 페리표 구매 규정, 활주로 폐쇄, 인구 감소는 관광 호황이라는 기사 흐름과 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0035",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PORTVILLE — The number of visitors to Portville rose sharply last summer, according to a report released by the city's tourism board. Nearly 600,000 tourists visited the coastal town between June and August, a 25 percent increase over the previous year. Officials credit the new ferry service connecting Portville with the regional airport. Local restaurants and shops have also reported record sales. Hotel owners, _______, say more accommodations are urgently needed. The city council will vote next month on a proposal to approve the construction of two new hotels.",
    "options": [
      "moreover",
      "therefore",
      "likewise",
      "however"
    ],
    "answer": 3,
    "explanation": "앞부분은 관광객 증가라는 긍정적 내용이고, 빈칸이 있는 문장은 '숙박 시설이 시급히 더 필요하다'는 호텔 업주들의 우려입니다. 긍정적 흐름에서 문제점 제기로 전환되므로 역접의 'however(그러나)'가 정답입니다. 콤마 사이에 삽입되는 접속부사 형태입니다. moreover(게다가)·likewise(마찬가지로)는 첨가·유사, therefore(그러므로)는 인과라 어울리지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0036",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PORTVILLE — The number of visitors to Portville rose sharply last summer, according to a report released by the city's tourism board. Nearly 600,000 tourists visited the coastal town between June and August, a 25 percent increase over the previous year. Officials credit the new ferry service connecting Portville with the regional airport. Local restaurants and shops have also reported record sales. Hotel owners, however, say more accommodations are urgently needed. The city council will vote next month on a proposal to _______ the construction of two new hotels.",
    "options": [
      "perform",
      "approve",
      "observe",
      "imply"
    ],
    "answer": 1,
    "explanation": "시의회가 표결하는 대상은 '두 호텔의 건설을 승인하는' 안건이므로 'approve(승인하다)'가 정답입니다. 'approve the construction(건설을 승인하다)'이 자연스러운 연어입니다. perform(수행하다), observe(관찰하다·준수하다), imply(암시하다)는 의회 표결의 목적어로 적절하지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0037",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "ATTENTION RESIDENTS\n\nRoutine maintenance will be performed on the building's elevators next week. Elevator A will be out of service on Monday and Tuesday, _______ Elevator B will be inspected on Wednesday and Thursday. At least one elevator will remain operational at all times. The work is expected to take about six hours each day. Residents who require special assistance during this period should contact the building manager in advance. We appreciate your patience as we work to keep our equipment safe and reliable.",
    "options": [
      "during",
      "while",
      "despite",
      "unless"
    ],
    "answer": 1,
    "explanation": "빈칸 뒤에 '주어(Elevator B) + 동사(will be inspected)'를 갖춘 완전한 절이 오므로 절을 이끌 수 있는 접속사 'while(~하는 한편, ~하는 동안)'이 정답입니다. 두 엘리베이터의 점검 일정을 대비시키는 역할을 합니다. during은 전치사라 절을 이끌 수 없고, despite도 전치사이며, unless(~하지 않는 한)는 의미상 어색합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0038",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "ATTENTION RESIDENTS\n\nRoutine maintenance will be performed on the building's elevators next week. Elevator A will be out of service on Monday and Tuesday, while Elevator B will be inspected on Wednesday and Thursday. At least one elevator will remain _______ at all times. The work is expected to take about six hours each day. Residents who require special assistance during this period should contact the building manager in advance. We appreciate your patience as we work to keep our equipment safe and reliable.",
    "options": [
      "voluntary",
      "temporary",
      "operational",
      "spacious"
    ],
    "answer": 2,
    "explanation": "점검 기간에도 '엘리베이터 한 대는 항상 가동 상태를 유지한다'는 의미이므로 '가동 중인, 운영되는'을 뜻하는 'operational'이 정답입니다. 'remain operational'은 시설 안내문의 빈출 표현입니다. voluntary(자발적인), temporary(일시적인), spacious(넓은)는 remain의 보어로 문맥에 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0039",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "ATTENTION RESIDENTS\n\nRoutine maintenance will be performed on the building's elevators next week. Elevator A will be out of service on Monday and Tuesday, while Elevator B will be inspected on Wednesday and Thursday. At least one elevator will remain operational at all times. _______ Residents who require special assistance during this period should contact the building manager in advance. We appreciate your patience as we work to keep our equipment safe and reliable.",
    "options": [
      "The work is expected to take about six hours each day.",
      "Rent increases will take effect next January.",
      "Both elevators were replaced five years ago.",
      "The lobby furniture has been reupholstered."
    ],
    "answer": 0,
    "explanation": "점검 일정과 가동 계획을 안내한 뒤, 입주민에게 사전 연락을 당부하기 전 위치이므로 '작업이 매일 약 6시간 걸릴 것으로 예상된다'는 작업 세부 정보가 들어가는 것이 가장 적절합니다. 임대료 인상, 5년 전 교체 이력, 로비 가구 교체는 다음 주 점검 안내라는 공지의 목적과 무관합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0040",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "ATTENTION RESIDENTS\n\nRoutine maintenance will be performed on the building's elevators next week. Elevator A will be out of service on Monday and Tuesday, while Elevator B will be inspected on Wednesday and Thursday. At least one elevator will remain operational at all times. The work is expected to take about six hours each day. Residents who require special assistance during this period should contact the building manager in advance. We appreciate your patience _______ we work to keep our equipment safe and reliable.",
    "options": [
      "so",
      "yet",
      "as",
      "or"
    ],
    "answer": 2,
    "explanation": "'저희가 장비를 안전하게 유지하기 위해 작업하는 동안 인내심에 감사드립니다'라는 의미이므로 '~하는 동안, ~하면서'를 뜻하는 접속사 'as'가 정답입니다. 'We appreciate your patience as we work ~'는 안내문의 상투적 마무리 표현입니다. so(그래서), yet(그러나), or(또는)는 시간적 동시성을 나타내지 못합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0041",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Okafor,\n\nThank you for applying for the senior accountant position at Brightway Solutions. We were impressed by your _______ and would like to invite you to an interview on Tuesday, September 9, at 2:00 P.M. The interview will last about one hour and will include a short skills assessment. Directions to our office are attached to this message. Please bring two copies of your résumé and a valid photo ID. If the proposed time is not convenient, let us know your availability, and we will be happy to reschedule. We look forward to meeting you in person.\n\nBest regards,\nHenry Lau, HR Manager",
    "options": [
      "possessions",
      "qualifications",
      "destinations",
      "celebrations"
    ],
    "answer": 1,
    "explanation": "채용 담당자가 지원자의 무엇에 '깊은 인상을 받아' 면접에 초대하는지 생각하면, '자격, 경력 요건'을 뜻하는 'qualifications'가 정답입니다. 'be impressed by one's qualifications'는 채용 서신의 전형적인 표현입니다. possessions(소유물), destinations(목적지), celebrations(축하 행사)는 채용 문맥에 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0042",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Okafor,\n\nThank you for applying for the senior accountant position at Brightway Solutions. We were impressed by your qualifications and would like to invite you to an interview on Tuesday, September 9, at 2:00 P.M. The interview will last about one hour and will include a short skills assessment. _______ Please bring two copies of your résumé and a valid photo ID. If the proposed time is not convenient, let us know your availability, and we will be happy to reschedule. We look forward to meeting you in person.\n\nBest regards,\nHenry Lau, HR Manager",
    "options": [
      "Our company was founded more than fifty years ago.",
      "The position has already been filled internally.",
      "Directions to our office are attached to this message.",
      "Accountants must renew their licenses every two years."
    ],
    "answer": 2,
    "explanation": "면접 일시와 진행 방식을 안내한 뒤, 지참물을 당부하는 문장 앞이므로 면접 방문에 필요한 '오시는 길 안내가 첨부되어 있다'는 문장이 가장 자연스럽습니다. 회사 연혁이나 회계사 면허 갱신 규정은 면접 안내와 직접 관련이 없고, '자리가 이미 내부에서 충원되었다'는 내용은 면접 초대라는 편지 목적과 정면으로 모순됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0043",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Okafor,\n\nThank you for applying for the senior accountant position at Brightway Solutions. We were impressed by your qualifications and would like to invite you to an interview on Tuesday, September 9, at 2:00 P.M. The interview will last about one hour and will include a short skills assessment. Directions to our office are attached to this message. Please bring two copies of your résumé and a valid photo ID. If the proposed time is not convenient, _______ us know your availability, and we will be happy to reschedule. We look forward to meeting you in person.\n\nBest regards,\nHenry Lau, HR Manager",
    "options": [
      "letting",
      "lets",
      "let",
      "to let"
    ],
    "answer": 2,
    "explanation": "'If ~, please의 생략된 명령문' 구조로, 콤마 뒤 주절이 명령문이므로 동사원형 'let'이 정답입니다. 'let us know(저희에게 알려 주세요)'는 비즈니스 서신의 빈출 표현입니다. letting·lets·to let은 명령문의 문두 동사 자리에 올 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0044",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Okafor,\n\nThank you for applying for the senior accountant position at Brightway Solutions. We were impressed by your qualifications and would like to invite you to an interview on Tuesday, September 9, at 2:00 P.M. The interview will last about one hour and will include a short skills assessment. Directions to our office are attached to this message. Please bring two copies of your résumé and a valid photo ID. If the proposed time is not convenient, let us know your availability, and we will be happy to reschedule. We look forward to meeting you _______.\n\nBest regards,\nHenry Lau, HR Manager",
    "options": [
      "at once",
      "in person",
      "by far",
      "on time"
    ],
    "answer": 1,
    "explanation": "면접 초대 편지의 마무리이므로 '직접 만나 뵙기를 기대합니다'라는 의미의 'in person(직접, 대면으로)'이 정답입니다. at once(즉시), by far(단연코), on time(제시간에)은 '만나 뵙기를 기대한다'는 인사말과 어울리지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0045",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Tran,\n\nOn behalf of the Westbrook Children's Library, I would like to thank you for your _______ donation of $2,500. Your gift will allow us to purchase new books and expand our weekend reading program. Demand for these services has grown steadily in recent years. Last year alone, more than 1,200 children participated in our free literacy workshops. Without your support, many of these programs would not be possible. A receipt for tax purposes is enclosed. We hope you will visit the library soon to see the difference your generosity has made.\n\nWarm regards,\nSamuel Ortiz, Director",
    "options": [
      "punctual",
      "durable",
      "generous",
      "fluent"
    ],
    "answer": 2,
    "explanation": "2,500달러의 기부에 감사를 표하는 문맥이므로 '후한, 너그러운'을 뜻하는 'generous'가 정답입니다. 'generous donation(후한 기부)'은 감사 서신의 대표적인 연어입니다. punctual(시간을 지키는), durable(내구성 있는), fluent(유창한)는 donation을 수식하기에 부적절합니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0046",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Tran,\n\nOn behalf of the Westbrook Children's Library, I would like to thank you for your generous donation of $2,500. Your gift will allow us to purchase new books and expand our weekend reading program. _______ Last year alone, more than 1,200 children participated in our free literacy workshops. Without your support, many of these programs would not be possible. A receipt for tax purposes is enclosed. We hope you will visit the library soon to see the difference your generosity has made.\n\nWarm regards,\nSamuel Ortiz, Director",
    "options": [
      "Demand for these services has grown steadily in recent years.",
      "The library was closed for repairs most of last year.",
      "Donations are no longer accepted at this time.",
      "Ms. Tran has applied for a librarian position."
    ],
    "answer": 0,
    "explanation": "기부금으로 주말 독서 프로그램을 확대하겠다고 한 뒤, 작년에 1,200명이 넘는 어린이가 워크숍에 참여했다는 통계가 이어집니다. 그 사이에는 '이러한 서비스에 대한 수요가 꾸준히 늘고 있다'는 문장이 들어가야 프로그램 확대의 필요성과 참여 통계가 자연스럽게 연결됩니다. 도서관 장기 휴관은 1,200명 참여 통계와 모순되고, 기부 중단이나 구직 지원은 감사 편지의 흐름에 맞지 않습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0047",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Tran,\n\nOn behalf of the Westbrook Children's Library, I would like to thank you for your generous donation of $2,500. Your gift will allow us to purchase new books and expand our weekend reading program. Demand for these services has grown steadily in recent years. Last year alone, more than 1,200 children participated in our free literacy workshops. _______ your support, many of these programs would not be possible. A receipt for tax purposes is enclosed. We hope you will visit the library soon to see the difference your generosity has made.\n\nWarm regards,\nSamuel Ortiz, Director",
    "options": [
      "Without",
      "Despite",
      "Among",
      "Beyond"
    ],
    "answer": 0,
    "explanation": "'당신의 후원이 없다면 이 프로그램들 중 다수는 불가능할 것'이라는 의미이므로 '~이 없다면'을 뜻하는 'Without'이 정답입니다. 'Without ~, would not be possible'은 가정의 의미를 담은 구조입니다. Despite(~에도 불구하고)를 쓰면 후원에도 불구하고 불가능하다는 모순된 의미가 되고, Among(~ 사이에), Beyond(~를 넘어)는 문맥에 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0048",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Ms. Tran,\n\nOn behalf of the Westbrook Children's Library, I would like to thank you for your generous donation of $2,500. Your gift will allow us to purchase new books and expand our weekend reading program. Demand for these services has grown steadily in recent years. Last year alone, more than 1,200 children participated in our free literacy workshops. Without your support, many of these programs would not be possible. A receipt for tax purposes is _______. We hope you will visit the library soon to see the difference your generosity has made.\n\nWarm regards,\nSamuel Ortiz, Director",
    "options": [
      "expired",
      "concluded",
      "dissolved",
      "enclosed"
    ],
    "answer": 3,
    "explanation": "'세금 처리용 영수증이 동봉되어 있습니다'라는 의미이므로 'enclosed(동봉된)'가 정답입니다. 'A receipt is enclosed'는 우편 서신에서 첨부물을 알리는 정형화된 표현입니다. expired(만료된), concluded(끝난), dissolved(해산된·용해된)는 영수증을 설명하는 말로 적절하지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0049",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Thank you for purchasing the AeroBrew 3000 coffee maker. To activate your two-year warranty, please register your product within thirty days of purchase. Begin by visiting our website and _______ the serial number printed on the bottom of the machine. The number can also be found on the side of the product box. Once your registration is complete, you will receive a confirmation e-mail within 24 hours. Keep your original receipt, as it may be required for warranty service. In addition, registered customers receive exclusive discounts on accessories and replacement filters.",
    "options": [
      "enter",
      "entering",
      "entered",
      "to entering"
    ],
    "answer": 1,
    "explanation": "전치사 by 뒤에서 'visiting'과 and로 병렬 연결되는 자리이므로 동명사 'entering'이 정답입니다. 'by visiting our website and entering the serial number(웹사이트를 방문하여 일련번호를 입력함으로써)'의 구조입니다. 병렬 구조에서는 같은 형태(동명사-동명사)를 맞춰야 하므로 enter, entered, to entering은 올 수 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0050",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Thank you for purchasing the AeroBrew 3000 coffee maker. To activate your two-year warranty, please register your product within thirty days of purchase. Begin by visiting our website and entering the serial number printed on the bottom of the machine. _______ Once your registration is complete, you will receive a confirmation e-mail within 24 hours. Keep your original receipt, as it may be required for warranty service. In addition, registered customers receive exclusive discounts on accessories and replacement filters.",
    "options": [
      "The number can also be found on the side of the product box.",
      "Coffee should be stored in an airtight container.",
      "Our factory produces over 10,000 units per month.",
      "The warranty does not cover the carafe."
    ],
    "answer": 0,
    "explanation": "바로 앞 문장에서 '기계 바닥에 인쇄된 일련번호를 입력하라'고 했으므로, 그 번호를 '제품 상자 옆면에서도 찾을 수 있다'고 보충하는 문장이 가장 자연스럽습니다. also가 앞 문장과의 연결을 보여 줍니다. 커피 보관법, 공장 생산량, 보증 제외 품목은 등록 절차 설명의 흐름을 끊습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0051",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Thank you for purchasing the AeroBrew 3000 coffee maker. To activate your two-year warranty, please register your product within thirty days of purchase. Begin by visiting our website and entering the serial number printed on the bottom of the machine. The number can also be found on the side of the product box. Once your registration is complete, you will receive a confirmation e-mail within 24 hours. Keep your original receipt, _______ it may be required for warranty service. In addition, registered customers receive exclusive discounts on accessories and replacement filters.",
    "options": [
      "or",
      "but",
      "nor",
      "as"
    ],
    "answer": 3,
    "explanation": "'영수증을 보관하세요, 보증 서비스에 필요할 수 있으므로'라는 의미로, 이유를 나타내는 접속사 'as(~이므로)'가 정답입니다. 앞은 당부, 뒤는 그 이유이므로 인과 관계의 접속사가 필요합니다. or(또는), but(그러나), nor(~도 아니다)는 이유를 나타낼 수 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0052",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Thank you for purchasing the AeroBrew 3000 coffee maker. To activate your two-year warranty, please register your product within thirty days of purchase. Begin by visiting our website and entering the serial number printed on the bottom of the machine. The number can also be found on the side of the product box. Once your registration is complete, you will receive a confirmation e-mail within 24 hours. Keep your original receipt, as it may be required for warranty service. _______, registered customers receive exclusive discounts on accessories and replacement filters.",
    "options": [
      "On the contrary",
      "In addition",
      "Even so",
      "In contrast"
    ],
    "answer": 1,
    "explanation": "앞에서 등록 시 확인 이메일과 보증 서비스를 설명했고, 빈칸 뒤에서는 '등록 고객은 액세서리 독점 할인도 받는다'는 또 다른 혜택을 덧붙입니다. 혜택이 첨가되는 흐름이므로 'In addition(게다가)'이 정답입니다. On the contrary(그와 반대로), Even so(그렇다 하더라도), In contrast(대조적으로)는 모두 대조·양보의 의미라 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0053",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Subscriber,\n\nYour annual subscription to Business Trends Weekly will _______ on July 31. Renew before July 15 to lock in the current rate of $89 per year. Prices will rise by 10 percent beginning August 1. Subscribers who renew early will also receive free access to our digital archive, which contains every issue published since 1998. To renew, simply log in to your account and click \"Renew Now.\" If you take no action, your access will end automatically, and no further charges will be made. We truly value your loyalty.\n\nSincerely,\nBusiness Trends Weekly",
    "options": [
      "resign",
      "vanish",
      "expire",
      "dissolve"
    ],
    "answer": 2,
    "explanation": "연간 구독이 7월 31일에 '만료된다'는 문맥이므로 'expire(만료되다)'가 정답입니다. 'subscription will expire on + 날짜'는 구독 갱신 안내문의 정형화된 표현입니다. resign(사임하다)은 사람이 주어일 때 쓰고, vanish(사라지다)와 dissolve(용해되다·해산하다)는 구독 종료를 나타내는 표현으로 쓰이지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0054",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Subscriber,\n\nYour annual subscription to Business Trends Weekly will expire on July 31. Renew before July 15 to lock in the current rate of $89 per year. _______ Subscribers who renew early will also receive free access to our digital archive, which contains every issue published since 1998. To renew, simply log in to your account and click \"Renew Now.\" If you take no action, your access will end automatically, and no further charges will be made. We truly value your loyalty.\n\nSincerely,\nBusiness Trends Weekly",
    "options": [
      "Prices will rise by 10 percent beginning August 1.",
      "Our magazine is printed on recycled paper.",
      "The archive will be deleted permanently next week.",
      "Most readers prefer the print edition."
    ],
    "answer": 0,
    "explanation": "앞 문장에서 '7월 15일 이전에 갱신하면 현재 요금을 고정할 수 있다(lock in the current rate)'고 했으므로, 그 이유를 설명하는 '8월 1일부터 가격이 10퍼센트 인상된다'는 문장이 가장 논리적으로 이어집니다. 재생지 인쇄, 종이판 선호는 갱신 권유와 무관하고, 아카이브 영구 삭제는 '1998년 이후 모든 호가 담긴 아카이브 무료 이용' 혜택과 모순됩니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0055",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Subscriber,\n\nYour annual subscription to Business Trends Weekly will expire on July 31. Renew before July 15 to lock in the current rate of $89 per year. Prices will rise by 10 percent beginning August 1. Subscribers who renew early will also receive free access to our digital archive, which contains every issue published since 1998. To renew, simply log in to your account and click \"Renew Now.\" _______ you take no action, your access will end automatically, and no further charges will be made. We truly value your loyalty.\n\nSincerely,\nBusiness Trends Weekly",
    "options": [
      "Until",
      "If",
      "Whereas",
      "Though"
    ],
    "answer": 1,
    "explanation": "'아무 조치를 취하지 않으면 이용 권한이 자동으로 종료된다'는 조건의 의미이므로 'If(만약 ~라면)'가 정답입니다. 조건절과 그 결과(자동 종료, 추가 청구 없음)가 자연스럽게 연결됩니다. Until(~까지), Whereas(~인 반면), Though(~이긴 하지만)는 조건의 의미를 나타내지 못합니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0056",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Subscriber,\n\nYour annual subscription to Business Trends Weekly will expire on July 31. Renew before July 15 to lock in the current rate of $89 per year. Prices will rise by 10 percent beginning August 1. Subscribers who renew early will also receive free access to our digital archive, which contains every issue published since 1998. To renew, simply log in to your account and click \"Renew Now.\" If you take no action, your access will end automatically, and no further charges will be made. We truly value your _______.\n\nSincerely,\nBusiness Trends Weekly",
    "options": [
      "curiosity",
      "anxiety",
      "vacancy",
      "loyalty"
    ],
    "answer": 3,
    "explanation": "구독 갱신을 권유하는 편지의 마무리 인사이므로 '고객의 충성도, 변함없는 성원'을 뜻하는 'loyalty'가 정답입니다. 'We value your loyalty(고객님의 성원에 감사드립니다)'는 고객 서신의 상투 표현입니다. curiosity(호기심), anxiety(불안), vacancy(공석)는 감사 인사의 대상이 될 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0057",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PUBLIC NOTICE — Marlowe City Library\n\nBeginning October 1, the library will extend its weekday hours and remain open _______ 9 P.M. Monday through Friday. Weekend hours will stay the same. The change comes in response to a survey in which residents requested more evening access. More than 800 residents responded to the questionnaire. Additional staff have been hired to cover the new schedule. Moreover, the study rooms on the second floor may now be reserved online up to two weeks in advance. We thank everyone who participated in the survey.\n\n— Library Administration",
    "options": [
      "by",
      "until",
      "at",
      "since"
    ],
    "answer": 1,
    "explanation": "'오후 9시까지 계속 문을 연다'는 지속의 의미이므로 'until(~까지 계속)'이 정답입니다. 'remain open until 9 P.M.'은 상태의 지속을 나타냅니다. by는 '늦어도 ~까지'라는 완료 기한을 나타내므로 remain과 어울리지 않고, at은 특정 시각, since는 '~ 이후로'라 문맥에 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0058",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PUBLIC NOTICE — Marlowe City Library\n\nBeginning October 1, the library will extend its weekday hours and remain open until 9 P.M. Monday through Friday. Weekend hours will stay the same. The change comes in response to a survey in which residents requested more evening access. _______ Additional staff have been hired to cover the new schedule. Moreover, the study rooms on the second floor may now be reserved online up to two weeks in advance. We thank everyone who participated in the survey.\n\n— Library Administration",
    "options": [
      "The library's book collection is the oldest in the county.",
      "More than 800 residents responded to the questionnaire.",
      "Late fees will double starting next month.",
      "The second floor is currently under construction."
    ],
    "answer": 1,
    "explanation": "앞 문장에서 '주민 설문 조사에 따라 운영 시간을 변경한다'고 했으므로, 그 설문의 규모를 보여 주는 '800명이 넘는 주민이 응답했다'는 문장이 들어가야 변경의 근거가 강화됩니다. 장서 역사나 연체료 인상은 흐름과 무관하고, 2층이 공사 중이라는 내용은 뒤에 나오는 '2층 스터디룸 온라인 예약 가능' 안내와 모순됩니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0059",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PUBLIC NOTICE — Marlowe City Library\n\nBeginning October 1, the library will extend its weekday hours and remain open until 9 P.M. Monday through Friday. Weekend hours will stay the same. The change comes in response to a survey in which residents requested more evening access. More than 800 residents responded to the questionnaire. Additional staff have been hired to cover the new schedule. _______, the study rooms on the second floor may now be reserved online up to two weeks in advance. We thank everyone who participated in the survey.\n\n— Library Administration",
    "options": [
      "However",
      "Instead",
      "Moreover",
      "Otherwise"
    ],
    "answer": 2,
    "explanation": "앞에서 '새 일정에 맞춰 직원을 추가 채용했다'는 개선 사항을 말했고, 빈칸 뒤에서 '2층 스터디룸 온라인 예약'이라는 또 다른 개선 사항을 덧붙이고 있습니다. 정보가 첨가되는 흐름이므로 'Moreover(게다가)'가 정답입니다. However(그러나)·Instead(대신에)·Otherwise(그렇지 않으면)는 첨가의 의미가 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0060",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "PUBLIC NOTICE — Marlowe City Library\n\nBeginning October 1, the library will extend its weekday hours and remain open until 9 P.M. Monday through Friday. Weekend hours will stay the same. The change comes in response to a survey in which residents requested more evening access. More than 800 residents responded to the questionnaire. Additional staff have been hired to cover the new schedule. Moreover, the study rooms on the second floor may now be reserved online up to two weeks in advance. We thank everyone _______ participated in the survey.\n\n— Library Administration",
    "options": [
      "who",
      "whom",
      "whose",
      "which"
    ],
    "answer": 0,
    "explanation": "선행사 'everyone(모든 분)'은 사람이고, 빈칸 뒤에 동사 'participated'가 바로 오므로 주격 관계대명사 'who'가 정답입니다. '설문에 참여해 주신 모든 분께 감사드립니다'라는 의미입니다. whom은 목적격, whose는 소유격이라 뒤에 동사가 바로 올 수 없고, which는 사물 선행사에 씁니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0061",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "HALSTON — Veritas Software was named Employer of the Year by the Halston Chamber of Commerce at its annual banquet on Friday. The award _______ companies that demonstrate outstanding commitment to employee development. Veritas, which employs over 300 people locally, offers tuition reimbursement and flexible working arrangements. Last year, nearly half of its staff took part in at least one training course. The company has grown considerably since moving its headquarters to Halston in 2019. It plans to hire fifty additional engineers by next spring.",
    "options": [
      "refuses",
      "recognizes",
      "reminds",
      "replaces"
    ],
    "answer": 1,
    "explanation": "'이 상은 직원 개발에 헌신하는 기업을 인정한다(공로를 기린다)'는 의미이므로 'recognizes(인정하다, 표창하다)'가 정답입니다. 'The award recognizes companies that ~'는 수상 관련 기사의 전형적인 표현입니다. refuses(거절하다), reminds(상기시키다), replaces(대체하다)는 상의 목적을 설명하는 동사로 적절하지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0062",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "HALSTON — Veritas Software was named Employer of the Year by the Halston Chamber of Commerce at its annual banquet on Friday. The award recognizes companies that demonstrate outstanding commitment to employee development. Veritas, which employs over 300 people locally, offers tuition reimbursement and flexible working arrangements. _______ The company has grown considerably since moving its headquarters to Halston in 2019. It plans to hire fifty additional engineers by next spring.",
    "options": [
      "Last year, nearly half of its staff took part in at least one training course.",
      "The banquet hall can accommodate 500 guests.",
      "Software prices have fallen across the industry.",
      "The chamber of commerce was established in 1921."
    ],
    "answer": 0,
    "explanation": "앞 문장에서 베리타스가 '학비 지원과 유연 근무'를 제공한다며 직원 개발 노력을 소개했으므로, 그 노력의 실제 성과인 '작년에 직원 절반 가까이가 교육 과정에 참여했다'는 문장이 들어가야 수상 이유가 구체화됩니다. 연회장 수용 인원, 업계 소프트웨어 가격, 상공회의소 설립 연도는 회사의 직원 개발이라는 기사 핵심과 무관합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0063",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "HALSTON — Veritas Software was named Employer of the Year by the Halston Chamber of Commerce at its annual banquet on Friday. The award recognizes companies that demonstrate outstanding commitment to employee development. Veritas, which employs over 300 people locally, offers tuition reimbursement and flexible working arrangements. Last year, nearly half of its staff took part in at least one training course. The company has grown _______ since moving its headquarters to Halston in 2019. It plans to hire fifty additional engineers by next spring.",
    "options": [
      "considerable",
      "considering",
      "considerate",
      "considerably"
    ],
    "answer": 3,
    "explanation": "자동사 'has grown(성장했다)'을 수식하는 자리이므로 부사 'considerably(상당히)'가 정답입니다. 'grow considerably'는 성장 폭을 강조하는 빈출 표현입니다. considerable(상당한)과 considerate(사려 깊은)는 형용사, considering은 전치사·분사라 동사를 수식할 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0064",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "HALSTON — Veritas Software was named Employer of the Year by the Halston Chamber of Commerce at its annual banquet on Friday. The award recognizes companies that demonstrate outstanding commitment to employee development. Veritas, which employs over 300 people locally, offers tuition reimbursement and flexible working arrangements. Last year, nearly half of its staff took part in at least one training course. The company has grown considerably since moving its headquarters to Halston in 2019. It plans to hire fifty _______ engineers by next spring.",
    "options": [
      "addition",
      "additionally",
      "additional",
      "additions"
    ],
    "answer": 2,
    "explanation": "빈칸 뒤의 명사 'engineers'를 수식하는 자리이므로 형용사 'additional(추가의)'이 정답입니다. 'fifty additional engineers(추가 엔지니어 50명)'의 구조입니다. addition/additions는 명사, additionally는 부사라 명사를 수식할 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0065",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Advance your career with LearnPath Online!\n\nOur project management certificate course begins on September 8 and runs for ten weeks. All lectures are recorded, so you can study _______ your own pace. Tuition includes textbooks, practice exams, and one-on-one coaching sessions. The certificate is recognized by leading employers nationwide. Graduates of the program report an average salary increase of 12 percent within one year. Enrollment is limited to ensure that every student receives personal attention. Moreover, early registrants save $150 on tuition. Sign up today at www.learnpath.com!",
    "options": [
      "on",
      "at",
      "in",
      "with"
    ],
    "answer": 1,
    "explanation": "'자신의 속도에 맞춰 공부하다'는 'at your own pace'라는 관용 표현을 쓰므로 'at'이 정답입니다. pace(속도) 앞에는 전치사 at을 쓰는 것이 굳어진 형태입니다. on, in, with는 pace와 결합하여 이 의미를 만들지 못합니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0066",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Advance your career with LearnPath Online!\n\nOur project management certificate course begins on September 8 and runs for ten weeks. All lectures are recorded, so you can study at your own pace. Tuition includes textbooks, practice exams, and one-on-one coaching sessions. _______ Graduates of the program report an average salary increase of 12 percent within one year. Enrollment is limited to ensure that every student receives personal attention. Moreover, early registrants save $150 on tuition. Sign up today at www.learnpath.com!",
    "options": [
      "Refunds are not available after the first week.",
      "The course was canceled last September.",
      "The certificate is recognized by leading employers nationwide.",
      "Our office is located near the train station."
    ],
    "answer": 2,
    "explanation": "수강료에 포함된 혜택을 나열한 뒤, '수료생의 평균 연봉이 12퍼센트 올랐다'는 성과가 이어지므로, 그 사이에는 '이 수료증이 전국 유수 기업에서 인정받는다'는 과정의 가치를 강조하는 문장이 가장 적절합니다. 환불 불가 조건은 광고의 설득 흐름을 깨고, 작년 과정 취소는 신뢰를 떨어뜨리며, 사무실 위치는 온라인 강좌 광고와 무관합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0067",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Advance your career with LearnPath Online!\n\nOur project management certificate course begins on September 8 and runs for ten weeks. All lectures are recorded, so you can study at your own pace. Tuition includes textbooks, practice exams, and one-on-one coaching sessions. The certificate is recognized by leading employers nationwide. Graduates of the program report an average salary increase of 12 percent within one year. Enrollment is limited to ensure that every student receives personal _______. Moreover, early registrants save $150 on tuition. Sign up today at www.learnpath.com!",
    "options": [
      "permission",
      "equipment",
      "ambition",
      "attention"
    ],
    "answer": 3,
    "explanation": "수강 인원을 제한하는 이유는 '모든 학생이 개별적인 관심(지도)을 받도록 하기 위해서'이므로 'attention(관심, 보살핌)'이 정답입니다. 'personal attention(개별 지도)'은 교육 광고의 빈출 연어입니다. permission(허가), equipment(장비), ambition(야망)은 personal과 결합해도 문맥에 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0068",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Advance your career with LearnPath Online!\n\nOur project management certificate course begins on September 8 and runs for ten weeks. All lectures are recorded, so you can study at your own pace. Tuition includes textbooks, practice exams, and one-on-one coaching sessions. The certificate is recognized by leading employers nationwide. Graduates of the program report an average salary increase of 12 percent within one year. Enrollment is limited to ensure that every student receives personal attention. _______, early registrants save $150 on tuition. Sign up today at www.learnpath.com!",
    "options": [
      "Nevertheless",
      "Otherwise",
      "Conversely",
      "Moreover"
    ],
    "answer": 3,
    "explanation": "앞에서 '인원 제한으로 개별 지도를 보장한다'는 장점을 말했고, 빈칸 뒤에서 '조기 등록자는 150달러를 절약한다'는 또 다른 혜택을 덧붙입니다. 혜택이 첨가되는 흐름이므로 'Moreover(게다가)'가 정답입니다. Nevertheless(그럼에도 불구하고), Otherwise(그렇지 않으면), Conversely(반대로)는 첨가 관계를 나타내지 못합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0069",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Jennings,\n\nYour lease for Apartment 4B at 22 Crescent Avenue is due to expire on November 30. We are pleased to offer you a twelve-month _______ at a monthly rent of $1,450, an increase of only $50. This rate is well below the average for similar units in the neighborhood. To accept this offer, please sign the enclosed agreement and return it to our office by October 15. Should you decide not to renew, kindly provide written notice at least sixty days before your lease ends. We have valued you as a tenant and sincerely hope you will choose to stay.\n\nSincerely,\nCrescent Property Management",
    "options": [
      "removal",
      "renewal",
      "reduction",
      "reception"
    ],
    "answer": 1,
    "explanation": "임대 계약 만료를 앞두고 '12개월 ____을 제안한다'는 문맥이므로 '갱신'을 뜻하는 'renewal'이 정답입니다. 'a twelve-month renewal(12개월 계약 갱신)'은 임대차 서신의 핵심 표현입니다. removal(제거·이사), reduction(감소), reception(접수·환영회)은 계약 연장 제안과 맞지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0070",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Jennings,\n\nYour lease for Apartment 4B at 22 Crescent Avenue is due to expire on November 30. We are pleased to offer you a twelve-month renewal at a monthly rent of $1,450, an increase of only $50. _______ To accept this offer, please sign the enclosed agreement and return it to our office by October 15. Should you decide not to renew, kindly provide written notice at least sixty days before your lease ends. We have valued you as a tenant and sincerely hope you will choose to stay.\n\nSincerely,\nCrescent Property Management",
    "options": [
      "The building was sold to a new owner last week.",
      "This rate is well below the average for similar units in the neighborhood.",
      "Apartment 4B has two bathrooms and a balcony.",
      "Utility bills must be paid directly to the city."
    ],
    "answer": 1,
    "explanation": "앞 문장에서 '월세 인상이 50달러에 불과하다'고 강조했으므로, 그 조건이 얼마나 유리한지 보여 주는 '이 금액은 인근 비슷한 매물의 평균보다 훨씬 낮다'는 문장이 들어가야 갱신을 설득하는 흐름이 완성됩니다. 건물 매각, 집 구조 설명, 공과금 납부 방식은 갱신 제안의 설득 논리와 연결되지 않습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0071",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Jennings,\n\nYour lease for Apartment 4B at 22 Crescent Avenue is due to expire on November 30. We are pleased to offer you a twelve-month renewal at a monthly rent of $1,450, an increase of only $50. This rate is well below the average for similar units in the neighborhood. To accept this offer, please sign the enclosed agreement and return it to our office by October 15. _______ you decide not to renew, kindly provide written notice at least sixty days before your lease ends. We have valued you as a tenant and sincerely hope you will choose to stay.\n\nSincerely,\nCrescent Property Management",
    "options": [
      "Would",
      "Could",
      "Should",
      "Might"
    ],
    "answer": 2,
    "explanation": "'_______ you decide not to renew'는 'If you should decide not to renew'에서 If가 생략되고 주어와 조동사가 도치된 형태이므로 'Should'가 정답입니다. 'Should you + 동사원형'은 격식 있는 서신에서 조건을 나타내는 빈출 구문입니다. Would, Could, Might는 이러한 조건 도치 구문을 만들지 못합니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0072",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Mr. Jennings,\n\nYour lease for Apartment 4B at 22 Crescent Avenue is due to expire on November 30. We are pleased to offer you a twelve-month renewal at a monthly rent of $1,450, an increase of only $50. This rate is well below the average for similar units in the neighborhood. To accept this offer, please sign the enclosed agreement and return it to our office by October 15. Should you decide not to renew, kindly provide written notice at least sixty days before your lease ends. We have valued you as a tenant and _______ hope you will choose to stay.\n\nSincerely,\nCrescent Property Management",
    "options": [
      "sincere",
      "sincerity",
      "sincerely",
      "sincerest"
    ],
    "answer": 2,
    "explanation": "동사 'hope'를 수식하는 자리이므로 부사 'sincerely(진심으로)'가 정답입니다. 'we sincerely hope(진심으로 바랍니다)'의 구조로, 동사를 수식할 수 있는 품사는 부사뿐입니다. sincere(형용사), sincerity(명사), sincerest(형용사 최상급)는 동사를 수식할 수 없습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0073",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Customer Service Staff\nFrom: Training Department\nRe: Software Training Sessions\n\nMandatory training on the new ticketing software will be held next week. Each session lasts two hours, and staff may choose _______ the Tuesday morning or the Thursday afternoon session. Attendance will be recorded, so please sign in upon arrival. Laptops will be provided, so no equipment is necessary. Those who miss both sessions must complete the online module by June 30. The new system officially launches on July 7, and the old program will be shut down the same day.",
    "options": [
      "both",
      "neither",
      "whether",
      "either"
    ],
    "answer": 3,
    "explanation": "빈칸 뒤에 'A or B(화요일 오전 세션 또는 목요일 오후 세션)' 구조가 있으므로 'either A or B(A 또는 B 둘 중 하나)'를 만드는 'either'가 정답입니다. both는 'both A and B', neither는 'neither A nor B'와 짝을 이루고, whether는 choose의 목적어 자리에서 이 구조로 쓰이지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0074",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Customer Service Staff\nFrom: Training Department\nRe: Software Training Sessions\n\nMandatory training on the new ticketing software will be held next week. Each session lasts two hours, and staff may choose either the Tuesday morning or the Thursday afternoon session. Attendance will be recorded, so please sign in upon _______. Laptops will be provided, so no equipment is necessary. Those who miss both sessions must complete the online module by June 30. The new system officially launches on July 7, and the old program will be shut down the same day.",
    "options": [
      "arrival",
      "removal",
      "approval",
      "denial"
    ],
    "answer": 0,
    "explanation": "'도착하는 즉시 서명(출석 체크)해 달라'는 의미이므로 'arrival(도착)'이 정답입니다. 'upon arrival(도착하자마자)'은 안내문의 정형화된 표현입니다. removal(제거), approval(승인), denial(부인)은 출석 체크 시점을 나타내는 말로 적절하지 않습니다.",
    "difficulty": "easy"
  },
  {
    "id": "p6-0075",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Customer Service Staff\nFrom: Training Department\nRe: Software Training Sessions\n\nMandatory training on the new ticketing software will be held next week. Each session lasts two hours, and staff may choose either the Tuesday morning or the Thursday afternoon session. Attendance will be recorded, so please sign in upon arrival. _______ Those who miss both sessions must complete the online module by June 30. The new system officially launches on July 7, and the old program will be shut down the same day.",
    "options": [
      "Laptops will be provided, so no equipment is necessary.",
      "The training department will move to the fifth floor.",
      "Customer complaints decreased sharply last quarter.",
      "The old software was purchased ten years ago."
    ],
    "answer": 0,
    "explanation": "교육 일정과 출석 절차를 안내한 뒤, 불참자 처리 규정으로 넘어가기 전이므로 참석 준비에 관한 '노트북이 제공되니 장비를 가져올 필요가 없다'는 안내가 가장 자연스럽습니다. 부서 이전, 고객 불만 감소 통계, 옛 소프트웨어 구입 시기는 교육 참석 안내라는 메모의 목적과 무관합니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0076",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "MEMO\nTo: All Customer Service Staff\nFrom: Training Department\nRe: Software Training Sessions\n\nMandatory training on the new ticketing software will be held next week. Each session lasts two hours, and staff may choose either the Tuesday morning or the Thursday afternoon session. Attendance will be recorded, so please sign in upon arrival. Laptops will be provided, so no equipment is necessary. Those who miss both sessions must complete the online module by June 30. The new system officially _______ on July 7, and the old program will be shut down the same day.",
    "options": [
      "launched",
      "has launched",
      "launches",
      "launching"
    ],
    "answer": 2,
    "explanation": "'on July 7'라는 확정된 미래 일정이 있고, 공식 일정·시간표처럼 정해진 미래는 현재시제로 나타낼 수 있으므로 'launches'가 정답입니다. 주어 'The new system'이 3인칭 단수이므로 -es 형태가 맞습니다. launched(과거)와 has launched(현재완료)는 미래 일정과 모순되고, launching은 본동사가 될 수 없습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0077",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Valued Customer,\n\nThank you for your recent order #58214. Unfortunately, the bookshelf you purchased is temporarily out of stock due to _______ high demand. We expect to ship your item by May 18, about one week later than originally estimated. As a gesture of goodwill, we will upgrade your delivery to express shipping at no extra cost. If you would prefer to cancel the order, you may do so at no charge through your account page. Alternatively, you can exchange the item for a similar model that is currently available. We apologize for the delay and appreciate your understanding.\n\nCustomer Care Team, Linden Home Goods",
    "options": [
      "unexpected",
      "unexpectedly",
      "expecting",
      "expectation"
    ],
    "answer": 1,
    "explanation": "빈칸 뒤의 형용사 'high'를 수식하는 자리이므로 부사 'unexpectedly(예상외로)'가 정답입니다. 'due to unexpectedly high demand(예상외로 높은 수요 때문에)'의 구조로, 형용사를 수식하는 품사는 부사입니다. unexpected는 형용사, expecting은 분사, expectation은 명사라 형용사 high를 수식할 수 없습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0078",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Valued Customer,\n\nThank you for your recent order #58214. Unfortunately, the bookshelf you purchased is temporarily out of stock due to unexpectedly high demand. We expect to ship your item by May 18, about one week later than originally _______. As a gesture of goodwill, we will upgrade your delivery to express shipping at no extra cost. If you would prefer to cancel the order, you may do so at no charge through your account page. Alternatively, you can exchange the item for a similar model that is currently available. We apologize for the delay and appreciate your understanding.\n\nCustomer Care Team, Linden Home Goods",
    "options": [
      "estimating",
      "estimates",
      "estimated",
      "estimation"
    ],
    "answer": 2,
    "explanation": "'당초 예상되었던 것보다 일주일 늦게'라는 의미로, 'than originally estimated'는 'than (it was) originally estimated'에서 주어와 be동사가 생략된 수동의 과거분사 형태입니다. 따라서 'estimated'가 정답입니다. estimating(능동), estimates(동사·명사), estimation(명사)은 이 생략 구문에 들어갈 수 없습니다.",
    "difficulty": "hard"
  },
  {
    "id": "p6-0079",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Valued Customer,\n\nThank you for your recent order #58214. Unfortunately, the bookshelf you purchased is temporarily out of stock due to unexpectedly high demand. We expect to ship your item by May 18, about one week later than originally estimated. _______ If you would prefer to cancel the order, you may do so at no charge through your account page. Alternatively, you can exchange the item for a similar model that is currently available. We apologize for the delay and appreciate your understanding.\n\nCustomer Care Team, Linden Home Goods",
    "options": [
      "As a gesture of goodwill, we will upgrade your delivery to express shipping at no extra cost.",
      "Our warehouse is located in three different states.",
      "Bookshelves are our most popular product category.",
      "Please assemble the item according to the manual."
    ],
    "answer": 0,
    "explanation": "배송 지연을 사과하고 새 배송 예정일을 알린 뒤이므로, 고객 불만을 달래기 위한 보상 조치인 '사과의 뜻으로 무료 특급 배송 업그레이드를 제공한다'는 문장이 가장 적절합니다. 창고 위치나 인기 상품 소개는 사과 편지의 흐름과 무관하고, 조립 안내는 아직 상품이 배송되지 않은 상황에 맞지 않습니다.",
    "difficulty": "medium"
  },
  {
    "id": "p6-0080",
    "part": 6,
    "type": "RC",
    "question": "Choose the best answer to fill in the blank.",
    "passage": "Dear Valued Customer,\n\nThank you for your recent order #58214. Unfortunately, the bookshelf you purchased is temporarily out of stock due to unexpectedly high demand. We expect to ship your item by May 18, about one week later than originally estimated. As a gesture of goodwill, we will upgrade your delivery to express shipping at no extra cost. If you would prefer to cancel the order, you may do so at no charge through your account page. _______, you can exchange the item for a similar model that is currently available. We apologize for the delay and appreciate your understanding.\n\nCustomer Care Team, Linden Home Goods",
    "options": [
      "Consequently",
      "Similarly",
      "Alternatively",
      "Meanwhile"
    ],
    "answer": 2,
    "explanation": "앞 문장에서 '주문 취소'라는 선택지를 제시했고, 빈칸 뒤에서 '비슷한 모델로 교환'이라는 또 다른 선택지를 제시합니다. 두 가지 대안 중 하나를 고를 수 있다는 흐름이므로 'Alternatively(그 대신에, 다른 방법으로는)'가 정답입니다. Consequently(그 결과), Similarly(마찬가지로), Meanwhile(그동안에)은 대안 제시의 의미가 없습니다.",
    "difficulty": "medium"
  }
];
